# Generated by Django 5.2 on 2026-03-21 02:18

import django.db.models.deletion
import django.utils.timezone
import eims_app.models.model_file_manage
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FileManage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file_name",
                    models.CharField(
                        help_text="请输入文件名称",
                        max_length=255,
                        verbose_name="文件名称",
                    ),
                ),
                (
                    "file_path",
                    models.FileField(
                        help_text="请选择上传文件",
                        upload_to=eims_app.models.model_file_manage.file_upload_path,
                        verbose_name="文件路径",
                    ),
                ),
                (
                    "uploader",
                    models.CharField(
                        help_text="请输入上传人姓名",
                        max_length=100,
                        verbose_name="上传人",
                    ),
                ),
                (
                    "upload_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="上传时间"),
                ),
                (
                    "file_size",
                    models.BigIntegerField(default=0, verbose_name="文件大小（字节）"),
                ),
                (
                    "file_type",
                    models.CharField(
                        blank=True,
                        help_text="自动识别，无需输入",
                        max_length=50,
                        null=True,
                        verbose_name="文件类型",
                    ),
                ),
            ],
            options={
                "verbose_name": "文件",
                "verbose_name_plural": "文件管理",
                "ordering": ("-upload_time",),
            },
        ),
        migrations.CreateModel(
            name="InfoCollect",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "collect_name",
                    models.CharField(
                        help_text="请输入信息收集名称",
                        max_length=255,
                        verbose_name="收集名称",
                    ),
                ),
                (
                    "collect_date",
                    models.DateField(
                        help_text="请选择信息收集日期", verbose_name="收集日期"
                    ),
                ),
                (
                    "collector",
                    models.CharField(
                        help_text="请输入收集人员姓名",
                        max_length=100,
                        verbose_name="收集人员",
                    ),
                ),
                (
                    "status",
                    models.SmallIntegerField(
                        choices=[(0, "未收集"), (1, "收集ing"), (2, "已完成")],
                        default=0,
                        help_text="请选择收集状态",
                        verbose_name="收集状态",
                    ),
                ),
                (
                    "collect_content",
                    models.TextField(
                        blank=True,
                        help_text="可选，输入信息收集详细内容",
                        null=True,
                        verbose_name="收集内容",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        blank=True,
                        help_text="可选，输入信息来源（如客户、供应商）",
                        max_length=100,
                        null=True,
                        verbose_name="信息来源",
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "信息收集记录",
                "verbose_name_plural": "信息收集管理",
                "ordering": ("-collect_date",),
            },
        ),
        migrations.CreateModel(
            name="Notice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notice_code",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="公告编号"
                    ),
                ),
                (
                    "notice_title",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="公告标题"
                    ),
                ),
                (
                    "notice_type",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="公告类型"
                    ),
                ),
                (
                    "notice_scope",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="发布范围"
                    ),
                ),
                (
                    "notice_content",
                    models.TextField(blank=True, null=True, verbose_name="公告内容"),
                ),
                (
                    "attach_file",
                    models.FileField(
                        blank=True, null=True, upload_to="notices/", verbose_name="附件"
                    ),
                ),
                (
                    "publish_person",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="发布人"
                    ),
                ),
                (
                    "publish_time",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="发布时间"
                    ),
                ),
                (
                    "effective_date",
                    models.DateField(blank=True, null=True, verbose_name="生效日期"),
                ),
                (
                    "invalid_date",
                    models.DateField(blank=True, null=True, verbose_name="失效日期"),
                ),
                (
                    "notice_status",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="公告状态"
                    ),
                ),
                (
                    "read_count",
                    models.IntegerField(
                        blank=True, default=0, null=True, verbose_name="阅读次数"
                    ),
                ),
                (
                    "remark",
                    models.TextField(blank=True, null=True, verbose_name="备注说明"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="是否删除"),
                ),
            ],
            options={
                "verbose_name": "通知公告",
                "verbose_name_plural": "通知公告",
                "ordering": ["-publish_time"],
            },
        ),
        migrations.CreateModel(
            name="Contract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="是否删除"),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "草稿"),
                            ("signed", "已签署"),
                            ("executing", "执行中"),
                            ("completed", "已完成"),
                            ("terminated", "已终止"),
                            ("cancelled", "已取消"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                        verbose_name="合同状态",
                    ),
                ),
                (
                    "contract_type",
                    models.CharField(
                        choices=[
                            ("engineering", "工程合同"),
                            ("service", "服务合同"),
                            ("purchase", "采购合同"),
                            ("other", "其他合同"),
                        ],
                        db_index=True,
                        default="engineering",
                        max_length=20,
                        verbose_name="合同类型",
                    ),
                ),
                (
                    "contract_name",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        max_length=255,
                        verbose_name="合同名称",
                    ),
                ),
                (
                    "contract_code",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=50,
                        null=True,
                        unique=True,
                        verbose_name="合同编号",
                    ),
                ),
                (
                    "contract_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=12,
                        verbose_name="合同金额",
                    ),
                ),
                (
                    "signing_time",
                    models.DateField(
                        blank=True, db_index=True, null=True, verbose_name="签订时间"
                    ),
                ),
                (
                    "project_code",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=50,
                        verbose_name="项目编号",
                    ),
                ),
                (
                    "party_a",
                    models.CharField(blank=True, max_length=200, verbose_name="甲方"),
                ),
                (
                    "project_name",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="项目名称"
                    ),
                ),
                (
                    "project_address",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="项目地址"
                    ),
                ),
                (
                    "project_scale",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="项目规模"
                    ),
                ),
                (
                    "project_investment",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="项目投资(万元)",
                    ),
                ),
                (
                    "contract_party_a",
                    models.CharField(blank=True, max_length=200, verbose_name="甲方"),
                ),
                (
                    "contract_party_b",
                    models.CharField(blank=True, max_length=200, verbose_name="乙方"),
                ),
                (
                    "contract_text",
                    models.TextField(blank=True, verbose_name="合同文本"),
                ),
                (
                    "payment_agreement",
                    models.TextField(blank=True, verbose_name="付款协议"),
                ),
                (
                    "agreed_staffing",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="约定人员"
                    ),
                ),
                (
                    "service_period",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="服务期限"
                    ),
                ),
                (
                    "service_deadline",
                    models.DateField(
                        blank=True, null=True, verbose_name="服务截止日期"
                    ),
                ),
                (
                    "planned_start_time",
                    models.DateField(
                        blank=True, null=True, verbose_name="计划开始时间"
                    ),
                ),
                (
                    "estimated_completion_time",
                    models.DateField(
                        blank=True, null=True, verbose_name="预计完成时间"
                    ),
                ),
                (
                    "extension_agreement",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="延期协议"
                    ),
                ),
                ("remark", models.TextField(blank=True, verbose_name="备注")),
            ],
            options={
                "verbose_name": "合同信息",
                "verbose_name_plural": "合同信息",
                "db_table": "eims_app_Contract",
                "indexes": [
                    models.Index(
                        fields=["status", "-signing_time"],
                        name="eims_app_Co_status_cc4add_idx",
                    ),
                    models.Index(
                        fields=["contract_type", "-signing_time"],
                        name="eims_app_Co_contrac_c25797_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "project_code",
                    models.CharField(
                        db_index=True,
                        help_text="唯一标识，用于关联合同表的project_code字段",
                        max_length=50,
                        unique=True,
                        verbose_name="项目编号",
                    ),
                ),
                (
                    "project_name",
                    models.CharField(
                        db_index=True, max_length=200, verbose_name="项目名称"
                    ),
                ),
                (
                    "project_category",
                    models.CharField(
                        choices=[
                            ("infrastructure", "基础设施"),
                            ("construction", "房屋建筑"),
                            ("municipal", "市政工程"),
                            ("transportation", "交通工程"),
                            ("water", "水利工程"),
                            ("other", "其他"),
                        ],
                        max_length=20,
                        verbose_name="项目类别",
                    ),
                ),
                (
                    "project_address",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="项目地址"
                    ),
                ),
                (
                    "project_scale",
                    models.CharField(
                        blank=True,
                        help_text="如：建筑面积5万㎡/道路长度10km",
                        max_length=100,
                        verbose_name="项目规模",
                    ),
                ),
                (
                    "project_investment",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="计划总投资额",
                        max_digits=15,
                        null=True,
                        verbose_name="项目投资(万元)",
                    ),
                ),
                (
                    "notice_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="进场通知书日期"
                    ),
                ),
                (
                    "entry_time",
                    models.DateField(blank=True, null=True, verbose_name="进场时间"),
                ),
                (
                    "actual_start_time",
                    models.DateField(
                        blank=True, null=True, verbose_name="实际开工时间"
                    ),
                ),
                (
                    "planned_completion_time",
                    models.DateField(
                        blank=True, null=True, verbose_name="预计竣工时间"
                    ),
                ),
                (
                    "project_status",
                    models.CharField(
                        choices=[
                            ("not_started", "未开工"),
                            ("normal_construction", "正常施工"),
                            ("stopped", "在停工"),
                            ("completed", "已完工"),
                        ],
                        default="not_started",
                        max_length=20,
                        verbose_name="项目状态",
                    ),
                ),
                (
                    "is_delayed",
                    models.BooleanField(default=False, verbose_name="是否延期"),
                ),
                (
                    "delay_status",
                    models.CharField(
                        blank=True,
                        help_text="如：延期45天（自动计算）",
                        max_length=100,
                        verbose_name="延期情况",
                    ),
                ),
                (
                    "delay_description",
                    models.TextField(blank=True, verbose_name="延期说明"),
                ),
                (
                    "project_manager",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="项目负责人"
                    ),
                ),
                (
                    "project_director",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=50,
                        verbose_name="项目总监",
                    ),
                ),
                (
                    "actual_manager",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=50,
                        verbose_name="实际负责人",
                    ),
                ),
                ("remark", models.TextField(blank=True, verbose_name="备注")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "项目",
                "verbose_name_plural": "项目管理",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["project_code", "project_name"],
                        name="eims_app_pr_project_fbf0c6_idx",
                    ),
                    models.Index(
                        fields=["project_category", "project_status"],
                        name="eims_app_pr_project_e60ebe_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Personnel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "personnel_code",
                    models.CharField(
                        default="PER001",
                        help_text="请输入唯一的人员编号",
                        max_length=50,
                        unique=True,
                        verbose_name="人员编号",
                    ),
                ),
                (
                    "project_code",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        max_length=50,
                        verbose_name="项目编号",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="",
                        help_text="请输入人员姓名",
                        max_length=50,
                        verbose_name="姓名",
                    ),
                ),
                (
                    "gender",
                    models.SmallIntegerField(
                        choices=[(0, "男"), (1, "女"), (2, "其他")],
                        default=0,
                        help_text="请选择人员性别",
                        verbose_name="性别",
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="请输入人员岗位",
                        max_length=100,
                        verbose_name="岗位",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        default="13800000000",
                        help_text="请输入唯一手机号码",
                        max_length=20,
                        unique=True,
                        verbose_name="手机号码",
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        default="",
                        help_text="请输入所属部门",
                        max_length=100,
                        verbose_name="部门",
                    ),
                ),
                (
                    "entry_time",
                    models.DateField(
                        blank=True,
                        help_text="选择入岗时间",
                        null=True,
                        verbose_name="入岗时间",
                    ),
                ),
                (
                    "leave_time",
                    models.DateField(
                        blank=True,
                        help_text="选择离岗时间",
                        null=True,
                        verbose_name="离岗时间",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        help_text="可选，输入人员邮箱",
                        max_length=254,
                        null=True,
                        verbose_name="邮箱",
                    ),
                ),
                (
                    "operator",
                    models.CharField(blank=True, max_length=100, verbose_name="操作人"),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "remark",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="可选，输入备注信息",
                        null=True,
                        verbose_name="备注",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        help_text="选择关联的项目",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="eims_app.project",
                        verbose_name="所在项目",
                    ),
                ),
            ],
            options={
                "verbose_name": "项目人员",
                "verbose_name_plural": "项目人员管理",
                "ordering": ("-create_time",),
            },
        ),
        migrations.CreateModel(
            name="Inspection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "inspection_date",
                    models.DateField(
                        help_text="请选择巡检日期", verbose_name="巡检日期"
                    ),
                ),
                (
                    "inspector",
                    models.CharField(
                        help_text="请输入巡检人员姓名",
                        max_length=100,
                        verbose_name="巡检人员",
                    ),
                ),
                (
                    "status",
                    models.SmallIntegerField(
                        choices=[
                            (0, "未巡检"),
                            (1, "巡检中"),
                            (2, "已完成"),
                            (3, "有异常"),
                        ],
                        default=0,
                        help_text="请选择巡检状态",
                        verbose_name="巡检状态",
                    ),
                ),
                (
                    "inspection_content",
                    models.TextField(
                        blank=True,
                        help_text="可选，输入巡检详细内容",
                        null=True,
                        verbose_name="巡检内容",
                    ),
                ),
                (
                    "problem",
                    models.TextField(
                        blank=True,
                        help_text="可选，输入巡检发现的问题",
                        null=True,
                        verbose_name="发现问题",
                    ),
                ),
                (
                    "solution",
                    models.TextField(
                        blank=True,
                        help_text="可选，输入问题解决措施",
                        null=True,
                        verbose_name="解决措施",
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "project",
                    models.ForeignKey(
                        help_text="请选择关联的项目",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="eims_app.project",
                        verbose_name="关联项目",
                    ),
                ),
            ],
            options={
                "verbose_name": "巡检记录",
                "verbose_name_plural": "巡检管理",
                "ordering": ("-inspection_date",),
            },
        ),
        migrations.CreateModel(
            name="ProjectDynamic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "project_code",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        max_length=50,
                        verbose_name="项目编号",
                    ),
                ),
                (
                    "project_progress",
                    models.CharField(
                        blank=True,
                        help_text="如：地基施工中/主体封顶/装修阶段",
                        max_length=100,
                        verbose_name="项目进度",
                    ),
                ),
                (
                    "project_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("not_started", "未开工"),
                            ("normal_construction", "正常施工"),
                            ("stopped", "在停工"),
                            ("completed", "已完工"),
                        ],
                        max_length=20,
                        verbose_name="项目状态",
                    ),
                ),
                (
                    "notice_entry",
                    models.DateField(
                        blank=True,
                        help_text="通知进场日期",
                        null=True,
                        verbose_name="通知进场",
                    ),
                ),
                (
                    "delay_status",
                    models.CharField(
                        blank=True,
                        help_text="描述延期情况",
                        max_length=200,
                        verbose_name="延期情况",
                    ),
                ),
                (
                    "planned_start_time",
                    models.DateField(
                        blank=True, null=True, verbose_name="计划开工时间"
                    ),
                ),
                (
                    "actual_start_time",
                    models.DateField(
                        blank=True, null=True, verbose_name="实际开工时间"
                    ),
                ),
                (
                    "planned_completion",
                    models.DateField(
                        blank=True, null=True, verbose_name="预计竣工时间"
                    ),
                ),
                (
                    "personnel_change",
                    models.CharField(
                        blank=True,
                        help_text="如：新增3人/离职1人",
                        max_length=200,
                        verbose_name="本月人员变动",
                    ),
                ),
                (
                    "operator",
                    models.CharField(blank=True, max_length=100, verbose_name="操作人"),
                ),
                ("remark", models.TextField(blank=True, verbose_name="备注")),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        help_text="选择关联的项目",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="eims_app.project",
                        verbose_name="关联项目",
                    ),
                ),
            ],
            options={
                "verbose_name": "项目动态",
                "verbose_name_plural": "项目动态管理",
                "ordering": ("-update_time",),
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "real_name",
                    models.CharField(blank=True, max_length=50, verbose_name="姓名"),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[("male", "男"), ("female", "女"), ("other", "其他")],
                        max_length=10,
                        verbose_name="性别",
                    ),
                ),
                (
                    "birthday",
                    models.DateField(blank=True, null=True, verbose_name="生日"),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=20, verbose_name="手机号"),
                ),
                (
                    "wechat",
                    models.CharField(blank=True, max_length=50, verbose_name="微信号"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "用户资料",
                "verbose_name_plural": "用户资料",
            },
        ),
        migrations.CreateModel(
            name="OutputPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "project_code",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        max_length=50,
                        verbose_name="项目编号",
                    ),
                ),
                (
                    "month",
                    models.CharField(
                        default="2026-01",
                        help_text="格式：YYYY-MM",
                        max_length=7,
                        verbose_name="月份",
                    ),
                ),
                (
                    "monthly_output",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="当月产值(万元)",
                    ),
                ),
                (
                    "cumulative_output",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="累计产值(万元)",
                    ),
                ),
                (
                    "contract_total",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="合同总额(元)",
                    ),
                ),
                (
                    "cumulative_received",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="累计已收款(元)",
                    ),
                ),
                (
                    "contract_receivable",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="合同应收款(元)",
                    ),
                ),
                (
                    "near_term_receivable",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="近期待收款(元)",
                    ),
                ),
                (
                    "payment_basis",
                    models.TextField(
                        blank=True, default="", verbose_name="合同付款依据"
                    ),
                ),
                (
                    "last_payment_situation",
                    models.TextField(
                        blank=True, default="", verbose_name="上次回款情况"
                    ),
                ),
                (
                    "recent_payment_request",
                    models.TextField(
                        blank=True, default="", verbose_name="近期请款情况"
                    ),
                ),
                (
                    "actual_payment",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="本月实际回款(元)",
                    ),
                ),
                (
                    "next_month_request",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=200,
                        verbose_name="下个月请款",
                    ),
                ),
                (
                    "next_month_plan",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="下月计划收款(元)",
                    ),
                ),
                (
                    "payment_measures",
                    models.TextField(blank=True, default="", verbose_name="请款措施"),
                ),
                (
                    "need_assistance",
                    models.TextField(blank=True, default="", verbose_name="需要协助"),
                ),
                (
                    "remark",
                    models.TextField(blank=True, default="", verbose_name="备注"),
                ),
                (
                    "payment_date",
                    models.DateField(
                        blank=True,
                        help_text="请选择回款日期",
                        null=True,
                        verbose_name="回款日期",
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="如银行转账、现金",
                        max_length=50,
                        verbose_name="回款方式",
                    ),
                ),
                (
                    "output_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="产值金额",
                    ),
                ),
                (
                    "payment_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="回款金额",
                    ),
                ),
                (
                    "operator",
                    models.CharField(blank=True, max_length=100, verbose_name="操作人"),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        help_text="选择关联的项目",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="eims_app.project",
                        verbose_name="关联项目",
                    ),
                ),
            ],
            options={
                "verbose_name": "产值回款",
                "verbose_name_plural": "产值回款管理",
                "ordering": ("-month", "-create_time"),
                "unique_together": {("project", "month")},
            },
        ),
        migrations.CreateModel(
            name="MonthlyReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "project_code",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=50,
                        verbose_name="项目编号",
                    ),
                ),
                ("report_year", models.IntegerField(verbose_name="填报年份")),
                ("report_month", models.IntegerField(verbose_name="填报月份")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "草稿"),
                            ("submitted", "已提交"),
                            ("overdue", "已逾期"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="填报状态",
                    ),
                ),
                (
                    "project_progress",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="描述当前项目进度情况",
                        verbose_name="项目进度说明",
                    ),
                ),
                (
                    "current_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("not_started", "未开工"),
                            ("normal_construction", "正常施工"),
                            ("stopped", "在停工"),
                            ("completed", "已完工"),
                        ],
                        default="",
                        max_length=20,
                        verbose_name="当前状态",
                    ),
                ),
                (
                    "monthly_output_value",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="本月实际完成的产值金额",
                        max_digits=15,
                        verbose_name="本月完成产值 (万元)",
                    ),
                ),
                (
                    "monthly_payment",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="本月实际收到的款项",
                        max_digits=15,
                        verbose_name="本月回款金额 (元)",
                    ),
                ),
                (
                    "payment_description",
                    models.TextField(
                        blank=True, default="", verbose_name="回款情况说明"
                    ),
                ),
                (
                    "personnel_changes",
                    models.TextField(
                        blank=True, default="", verbose_name="本月人员变动"
                    ),
                ),
                (
                    "total_personnel",
                    models.IntegerField(default=0, verbose_name="当前总人数"),
                ),
                (
                    "payment_request",
                    models.TextField(
                        blank=True, default="", verbose_name="本月请款情况"
                    ),
                ),
                (
                    "next_month_plan",
                    models.TextField(
                        blank=True, default="", verbose_name="下月工作计划"
                    ),
                ),
                (
                    "should_submit_date",
                    models.DateField(
                        blank=True,
                        help_text="每月 25 日为截止日期",
                        null=True,
                        verbose_name="应提交日期",
                    ),
                ),
                (
                    "actual_submit_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="实际提交日期"
                    ),
                ),
                (
                    "submit_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="提交时间"
                    ),
                ),
                (
                    "approve_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="审核时间"
                    ),
                ),
                (
                    "reject_reason",
                    models.TextField(blank=True, default="", verbose_name="退回原因"),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "approver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_reports",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="审核人",
                    ),
                ),
                (
                    "reporter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="填报人",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="eims_app.project",
                        verbose_name="填报项目",
                    ),
                ),
            ],
            options={
                "verbose_name": "月度报告",
                "verbose_name_plural": "月度报告管理",
                "ordering": ["-report_year", "-report_month", "-create_time"],
                "indexes": [
                    models.Index(
                        fields=["report_year", "report_month"],
                        name="eims_app_mo_report__71dc42_idx",
                    ),
                    models.Index(
                        fields=["status"], name="eims_app_mo_status_0a8abe_idx"
                    ),
                ],
                "unique_together": {("project", "report_year", "report_month")},
            },
        ),
        migrations.CreateModel(
            name="ProjectReporter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "report_period",
                    models.CharField(
                        choices=[
                            ("monthly", "月度"),
                            ("weekly", "周度"),
                            ("quarterly", "季度"),
                        ],
                        default="monthly",
                        max_length=20,
                        verbose_name="填报周期",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否启用"),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="eims_app.project",
                        verbose_name="关联项目",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="填报人员",
                    ),
                ),
            ],
            options={
                "verbose_name": "项目填报人员",
                "verbose_name_plural": "项目填报人员管理",
                "unique_together": {("user", "project")},
            },
        ),
    ]
