# Generated by Django 5.2 on 2026-03-21 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eims_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="outputpayment",
            name="is_deleted",
            field=models.BooleanField(default=False, verbose_name="是否删除"),
        ),
        migrations.AddField(
            model_name="personnel",
            name="is_deleted",
            field=models.BooleanField(default=False, verbose_name="是否删除"),
        ),
        migrations.AddField(
            model_name="projectdynamic",
            name="is_deleted",
            field=models.BooleanField(default=False, verbose_name="是否删除"),
        ),
    ]
