# Generated by Django 5.2 on 2026-03-21 04:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eims_app", "0002_outputpayment_is_deleted_personnel_is_deleted_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("super_admin", "超级管理员"),
                            ("system_admin", "系统管理员"),
                            ("project_director", "项目总监"),
                            ("director_rep", "总监代表"),
                            ("supervisor", "监理员"),
                            ("data_clerk", "资料员"),
                            ("initiator", "发起人"),
                        ],
                        max_length=50,
                        unique=True,
                        verbose_name="角色名称",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="角色描述")),
                (
                    "permissions",
                    models.TextField(
                        blank=True,
                        help_text="逗号分隔的权限代码",
                        verbose_name="权限列表",
                    ),
                ),
            ],
            options={
                "verbose_name": "角色",
                "verbose_name_plural": "角色管理",
            },
        ),
        migrations.CreateModel(
            name="ApprovalFlow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "current_step",
                    models.IntegerField(default=1, verbose_name="当前步骤"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "草稿"),
                            ("pending_review", "待总监审核"),
                            ("pending_approval", "待管理员审批"),
                            ("approved", "已批准"),
                            ("rejected", "已退回"),
                            ("cancelled", "已取消"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="流程状态",
                    ),
                ),
                (
                    "initiate_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="发起时间"),
                ),
                (
                    "director_review_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="总监审核时间"
                    ),
                ),
                (
                    "director_opinion",
                    models.TextField(blank=True, verbose_name="总监意见"),
                ),
                (
                    "director_passed",
                    models.BooleanField(
                        blank=True, null=True, verbose_name="总监审核是否通过"
                    ),
                ),
                (
                    "approval_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="管理员审批时间"
                    ),
                ),
                (
                    "approval_opinion",
                    models.TextField(blank=True, verbose_name="审批意见"),
                ),
                (
                    "approval_passed",
                    models.BooleanField(
                        blank=True, null=True, verbose_name="管理员审批是否通过"
                    ),
                ),
                (
                    "approver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="admin_approvals",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="审批管理员",
                    ),
                ),
                (
                    "director",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="director_reviews",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="项目总监",
                    ),
                ),
                (
                    "initiator",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="initiated_flows",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="发起人",
                    ),
                ),
                (
                    "report",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="eims_app.monthlyreport",
                        verbose_name="关联报告",
                    ),
                ),
            ],
            options={
                "verbose_name": "审批流程",
                "verbose_name_plural": "审批流程管理",
            },
        ),
        migrations.CreateModel(
            name="ApprovalRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("submit", "提交"),
                            ("review_pass", "审核通过"),
                            ("review_reject", "审核退回"),
                            ("approve_pass", "审批通过"),
                            ("approve_reject", "审批退回"),
                            ("cancel", "取消"),
                        ],
                        max_length=20,
                        verbose_name="操作类型",
                    ),
                ),
                ("opinion", models.TextField(blank=True, verbose_name="意见")),
                (
                    "action_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="操作时间"),
                ),
                (
                    "flow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="eims_app.approvalflow",
                        verbose_name="审批流程",
                    ),
                ),
                (
                    "operator",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="操作人",
                    ),
                ),
            ],
            options={
                "verbose_name": "审批记录",
                "verbose_name_plural": "审批记录管理",
                "ordering": ["-action_time"],
            },
        ),
        migrations.CreateModel(
            name="ProjectRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否启用"),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="eims_app.project",
                        verbose_name="项目",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="eims_app.role",
                        verbose_name="角色",
                    ),
                ),
            ],
            options={
                "verbose_name": "项目角色",
                "verbose_name_plural": "项目角色管理",
                "unique_together": {("user", "project", "role")},
            },
        ),
    ]
