# Generated by Django 5.2 on 2026-03-21 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eims_app", "0003_role_approvalflow_approvalrecord_projectrole"),
    ]

    operations = [
        migrations.AddField(
            model_name="personnel",
            name="address",
            field=models.CharField(
                blank=True,
                default="",
                help_text="填写详细住址",
                max_length=200,
                verbose_name="住址",
            ),
        ),
        migrations.AddField(
            model_name="personnel",
            name="admin_position",
            field=models.CharField(
                blank=True,
                default="",
                help_text="填写行政职务",
                max_length=100,
                verbose_name="行政职务",
            ),
        ),
        migrations.AddField(
            model_name="personnel",
            name="education",
            field=models.CharField(
                choices=[
                    ("primary", "小学"),
                    ("junior", "初中"),
                    ("senior", "高中"),
                    ("college", "大专"),
                    ("bachelor", "本科"),
                    ("master", "硕士"),
                    ("doctor", "博士"),
                ],
                default="bachelor",
                help_text="选择最高学历",
                max_length=20,
                verbose_name="学历",
            ),
        ),
        migrations.AddField(
            model_name="personnel",
            name="emergency_contact",
            field=models.CharField(
                blank=True,
                default="",
                help_text="填写应急联系人姓名",
                max_length=50,
                verbose_name="应急联系人",
            ),
        ),
        migrations.AddField(
            model_name="personnel",
            name="emergency_phone",
            field=models.CharField(
                blank=True,
                default="",
                help_text="填写应急联系电话",
                max_length=20,
                verbose_name="应急电话",
            ),
        ),
        migrations.AddField(
            model_name="personnel",
            name="ethnic",
            field=models.CharField(
                choices=[
                    ("han", "汉族"),
                    ("hui", "回族"),
                    ("man", "满族"),
                    ("mongol", "蒙古族"),
                    ("tibetan", "藏族"),
                    ("uyghur", "维吾尔族"),
                    ("other", "其他"),
                ],
                default="han",
                help_text="选择民族",
                max_length=20,
                verbose_name="民族",
            ),
        ),
        migrations.AddField(
            model_name="personnel",
            name="home_phone",
            field=models.CharField(
                blank=True,
                default="",
                help_text="家庭固定电话",
                max_length=20,
                verbose_name="固定电话",
            ),
        ),
        migrations.AddField(
            model_name="personnel",
            name="id_card",
            field=models.CharField(
                blank=True,
                help_text="18 位身份证号码",
                max_length=18,
                verbose_name="身份证号",
            ),
        ),
        migrations.AddField(
            model_name="personnel",
            name="job_qualification",
            field=models.CharField(
                blank=True,
                default="",
                help_text="填写任职资格",
                max_length=200,
                verbose_name="任职资格",
            ),
        ),
        migrations.AddField(
            model_name="personnel",
            name="mobile",
            field=models.CharField(
                default="",
                help_text="请输入手机号码",
                max_length=20,
                verbose_name="手机号",
            ),
        ),
        migrations.AddField(
            model_name="personnel",
            name="native_place",
            field=models.CharField(
                blank=True,
                default="",
                help_text="填写籍贯",
                max_length=100,
                verbose_name="籍贯",
            ),
        ),
        migrations.AddField(
            model_name="personnel",
            name="professional_qualification",
            field=models.CharField(
                blank=True,
                default="",
                help_text="填写执业资格证书名称",
                max_length=200,
                verbose_name="执业资格",
            ),
        ),
        migrations.AddField(
            model_name="personnel",
            name="professional_title",
            field=models.CharField(
                blank=True,
                default="",
                help_text="填写专业技术职称",
                max_length=100,
                verbose_name="职称",
            ),
        ),
        migrations.AddField(
            model_name="personnel",
            name="tech_position",
            field=models.CharField(
                blank=True,
                default="",
                help_text="填写技术职务",
                max_length=100,
                verbose_name="技术职务",
            ),
        ),
        migrations.AddField(
            model_name="personnel",
            name="wechat",
            field=models.CharField(
                blank=True,
                default="",
                help_text="填写微信号",
                max_length=50,
                verbose_name="微信",
            ),
        ),
        migrations.AlterField(
            model_name="monthlyreport",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "草稿"),
                    ("submitted", "已提交"),
                    ("overdue", "已逾期"),
                    ("pending_review", "待总监审核"),
                    ("pending_approval", "待管理员审批"),
                    ("approved", "已批准"),
                    ("rejected", "已退回"),
                ],
                default="draft",
                max_length=20,
                verbose_name="填报状态",
            ),
        ),
        migrations.AlterField(
            model_name="personnel",
            name="entry_time",
            field=models.DateField(
                blank=True, help_text="选择入职时间", null=True, verbose_name="入职时间"
            ),
        ),
        migrations.AlterField(
            model_name="personnel",
            name="leave_time",
            field=models.DateField(
                blank=True, help_text="选择离职时间", null=True, verbose_name="离职时间"
            ),
        ),
        migrations.AlterField(
            model_name="personnel",
            name="phone",
            field=models.CharField(
                default="",
                help_text="请输入手机号码",
                max_length=20,
                verbose_name="手机号码",
            ),
        ),
        migrations.CreateModel(
            name="PersonnelAllocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="是否删除"),
                ),
                (
                    "allocation_code",
                    models.CharField(
                        help_text="系统自动生成",
                        max_length=50,
                        unique=True,
                        verbose_name="分配编号",
                    ),
                ),
                (
                    "personnel_code",
                    models.CharField(
                        db_index=True, max_length=50, verbose_name="人员编号"
                    ),
                ),
                (
                    "from_project_code",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="原项目编号"
                    ),
                ),
                (
                    "to_project_code",
                    models.CharField(max_length=50, verbose_name="分配项目编号"),
                ),
                (
                    "allocation_position",
                    models.CharField(
                        help_text="填写在新项目的岗位",
                        max_length=100,
                        verbose_name="分配岗位",
                    ),
                ),
                (
                    "allocation_date",
                    models.DateField(
                        help_text="选择分配生效日期", verbose_name="分配日期"
                    ),
                ),
                (
                    "expected_duration",
                    models.CharField(
                        blank=True,
                        help_text="填写预计工作期限",
                        max_length=50,
                        verbose_name="预计工期",
                    ),
                ),
                (
                    "allocation_status",
                    models.CharField(
                        choices=[
                            ("allocated", "已分配"),
                            ("pending", "待分配"),
                            ("recalled", "已召回"),
                            ("transferred", "已调动"),
                        ],
                        default="allocated",
                        max_length=20,
                        verbose_name="分配状态",
                    ),
                ),
                (
                    "allocation_reason",
                    models.TextField(
                        blank=True,
                        help_text="填写分配原因说明",
                        verbose_name="分配原因",
                    ),
                ),
                (
                    "remark",
                    models.TextField(
                        blank=True,
                        help_text="可选，输入备注信息",
                        null=True,
                        verbose_name="备注",
                    ),
                ),
                (
                    "operator",
                    models.CharField(blank=True, max_length=100, verbose_name="操作人"),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "from_project",
                    models.ForeignKey(
                        blank=True,
                        help_text="选择原项目",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="from_projects",
                        to="eims_app.project",
                        verbose_name="原项目",
                    ),
                ),
                (
                    "personnel",
                    models.ForeignKey(
                        help_text="选择被分配的人员",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="eims_app.personnel",
                        verbose_name="人员",
                    ),
                ),
                (
                    "to_project",
                    models.ForeignKey(
                        help_text="选择分配到的项目",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="to_projects",
                        to="eims_app.project",
                        verbose_name="分配项目",
                    ),
                ),
            ],
            options={
                "verbose_name": "人员分配",
                "verbose_name_plural": "人员分配管理",
                "ordering": ("-allocation_date",),
            },
        ),
        migrations.CreateModel(
            name="PersonnelCertificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="是否删除"),
                ),
                (
                    "certificate_code",
                    models.CharField(
                        help_text="请输入证书编号",
                        max_length=50,
                        unique=True,
                        verbose_name="证书编号",
                    ),
                ),
                (
                    "personnel_code",
                    models.CharField(
                        db_index=True, max_length=50, verbose_name="人员编号"
                    ),
                ),
                (
                    "certificate_name",
                    models.CharField(
                        help_text="填写证书全称",
                        max_length=200,
                        verbose_name="证书名称",
                    ),
                ),
                (
                    "certificate_type",
                    models.CharField(
                        choices=[
                            ("qualification", "职业资格证书"),
                            ("training", "培训证书"),
                            ("academic", "学历证书"),
                            ("technical", "专业技术证书"),
                            ("other", "其他证书"),
                        ],
                        max_length=20,
                        verbose_name="证书类型",
                    ),
                ),
                (
                    "issuing_authority",
                    models.CharField(
                        help_text="填写发证机关全称",
                        max_length=200,
                        verbose_name="发证机关",
                    ),
                ),
                (
                    "issue_date",
                    models.DateField(
                        help_text="选择证书发放日期", verbose_name="发证日期"
                    ),
                ),
                (
                    "valid_date",
                    models.DateField(
                        blank=True,
                        help_text="选择证书有效期截止日期",
                        null=True,
                        verbose_name="有效期至",
                    ),
                ),
                (
                    "certificate_file",
                    models.FileField(
                        blank=True,
                        help_text="可上传证书扫描件",
                        null=True,
                        upload_to="certificates/%Y/%m/",
                        verbose_name="证书附件",
                    ),
                ),
                (
                    "remark",
                    models.TextField(
                        blank=True,
                        help_text="可选，输入备注信息",
                        null=True,
                        verbose_name="备注",
                    ),
                ),
                (
                    "operator",
                    models.CharField(blank=True, max_length=100, verbose_name="操作人"),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "personnel",
                    models.ForeignKey(
                        help_text="选择证书所属人员",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="eims_app.personnel",
                        verbose_name="所属人员",
                    ),
                ),
            ],
            options={
                "verbose_name": "人员证书",
                "verbose_name_plural": "人员证书管理",
                "ordering": ("-create_time",),
            },
        ),
    ]
