# Generated by Django 4.2.7 on 2026-04-14 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eims_app', '0003_add_company_executive_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyexecutiverole',
            name='tenant',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='数据隔离依据', null=True, on_delete=django.db.models.deletion.PROTECT, to='eims_app.tenant', verbose_name='所属公司'),
        ),
        migrations.AlterField(
            model_name='approvalchain',
            name='level_1_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='level_1_chains', to='eims_app.departmentrole', verbose_name='一级审批角色(部门)'),
        ),
        migrations.AlterField(
            model_name='approvalchain',
            name='level_2_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='level_2_chains', to='eims_app.departmentrole', verbose_name='二级审批角色(部门)'),
        ),
        migrations.AlterField(
            model_name='approvalchain',
            name='level_3_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='level_3_chains', to='eims_app.departmentrole', verbose_name='三级审批角色(部门)'),
        ),
        migrations.AlterField(
            model_name='companyexecutiverole',
            name='role_name',
            field=models.CharField(help_text='如：董事长、总经理等', max_length=50, verbose_name='角色名称'),
        ),
    ]
