# Generated by Django 4.2.7 on 2026-04-15 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eims_app', '0004_add_tenant_to_executive_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, verbose_name='子模块代码')),
                ('name', models.CharField(max_length=100, verbose_name='子模块名称')),
                ('icon', models.CharField(default='bi-circle', help_text='Bootstrap Icons class，如 bi-file-text', max_length=50, verbose_name='图标')),
                ('url_name', models.CharField(blank=True, help_text='Django URL name，如 eims_app:contract_approval_chain', max_length=100, verbose_name='URL名称')),
                ('url_pattern', models.CharField(blank=True, help_text='用于高亮当前菜单，如 /contract-approval', max_length=200, verbose_name='URL匹配模式')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('parent_module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submodules', to='eims_app.tenantmodule', verbose_name='所属一级模块')),
            ],
            options={
                'verbose_name': '子模块定义',
                'verbose_name_plural': '子模块定义',
                'db_table': 'eims_sub_module',
                'ordering': ['sort_order', 'code'],
                'unique_together': {('parent_module', 'code')},
            },
        ),
        migrations.AlterField(
            model_name='personnel',
            name='project',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='选择当前主要归属项目（可选）', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main_personnel', to='eims_app.projectdetail', verbose_name='主要项目'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='project2',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='选择第二个项目（可选）', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personnel_project2', to='eims_app.projectdetail', verbose_name='项目 2'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='project3',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='选择第三个项目（可选）', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personnel_project3', to='eims_app.projectdetail', verbose_name='项目 3'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='project4',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='选择第四个项目（可选）', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personnel_project4', to='eims_app.projectdetail', verbose_name='项目 4'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='project5',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='选择第五个项目（可选）', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personnel_project5', to='eims_app.projectdetail', verbose_name='项目 5'),
        ),
        migrations.CreateModel(
            name='TenantSubModulePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='是否启用')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('sub_module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_permissions', to='eims_app.submodule', verbose_name='子模块')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_module_permissions', to='eims_app.tenant', verbose_name='租户公司')),
            ],
            options={
                'verbose_name': '租户子模块权限',
                'verbose_name_plural': '租户子模块权限',
                'db_table': 'eims_tenant_sub_module_permission',
                'unique_together': {('tenant', 'sub_module')},
            },
        ),
    ]
