# Generated by Django 5.2 on 2026-03-21 09:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eims_app", "0004_personnel_address_personnel_admin_position_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="是否删除"),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "department_code",
                    models.CharField(
                        help_text="唯一部门标识",
                        max_length=50,
                        unique=True,
                        verbose_name="部门编号",
                    ),
                ),
                (
                    "department_name",
                    models.CharField(
                        help_text="部门全称", max_length=100, verbose_name="部门名称"
                    ),
                ),
                (
                    "department_type",
                    models.CharField(
                        choices=[
                            ("functional", "职能部门"),
                            ("project", "项目部门"),
                            ("temporary", "临时部门"),
                        ],
                        default="functional",
                        max_length=20,
                        verbose_name="部门类型",
                    ),
                ),
                (
                    "manager_name",
                    models.CharField(
                        blank=True,
                        help_text="部门经理/主任姓名",
                        max_length=50,
                        verbose_name="负责人姓名",
                    ),
                ),
                (
                    "contact_phone",
                    models.CharField(
                        blank=True,
                        help_text="部门负责人联系方式",
                        max_length=20,
                        verbose_name="联系电话",
                    ),
                ),
                (
                    "contact_email",
                    models.EmailField(
                        blank=True,
                        help_text="部门工作邮箱",
                        max_length=254,
                        verbose_name="联系邮箱",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="部门主要职责和工作范围",
                        verbose_name="部门描述",
                    ),
                ),
                (
                    "responsibilities",
                    models.TextField(
                        blank=True, help_text="详细职能说明", verbose_name="部门职能"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "正常"),
                            ("inactive", "停用"),
                            ("merging", "合并中"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="部门状态",
                    ),
                ),
                (
                    "established_date",
                    models.DateField(blank=True, null=True, verbose_name="成立日期"),
                ),
                (
                    "order",
                    models.IntegerField(
                        default=0, help_text="数字越小越靠前", verbose_name="排序顺序"
                    ),
                ),
                (
                    "manager",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="managed_departments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="部门负责人",
                    ),
                ),
                (
                    "parent_department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="child_departments",
                        to="eims_app.department",
                        verbose_name="上级部门",
                    ),
                ),
            ],
            options={
                "verbose_name": "部门",
                "verbose_name_plural": "部门管理",
                "ordering": ["parent_department", "order", "department_code"],
            },
        ),
        migrations.CreateModel(
            name="ApprovalChain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="是否删除"),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="如：人员分配审批流程",
                        max_length=100,
                        verbose_name="审批链名称",
                    ),
                ),
                (
                    "business_type",
                    models.CharField(
                        choices=[
                            ("personnel_allocate", "人员分配"),
                            ("personnel_transfer", "人员调动"),
                            ("leave_apply", "请假申请"),
                            ("expense_apply", "费用报销"),
                            ("contract_sign", "合同签订"),
                            ("payment_apply", "付款申请"),
                            ("other", "其他"),
                        ],
                        max_length=30,
                        verbose_name="业务类型",
                    ),
                ),
                (
                    "chain_type",
                    models.CharField(
                        choices=[
                            ("sequential", "逐级审批"),
                            ("parallel", "并行审批"),
                            ("hybrid", "混合审批"),
                        ],
                        default="sequential",
                        max_length=20,
                        verbose_name="审批类型",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="审批链描述"),
                ),
                (
                    "level_1_role",
                    models.CharField(
                        help_text="如：部门经理",
                        max_length=50,
                        verbose_name="一级审批角色",
                    ),
                ),
                (
                    "level_2_role",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="二级审批角色"
                    ),
                ),
                (
                    "level_3_role",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="三级审批角色"
                    ),
                ),
                (
                    "need_cross_department",
                    models.BooleanField(
                        default=False, verbose_name="是否需要跨部门协同"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否启用"),
                ),
                (
                    "cross_departments",
                    models.ManyToManyField(
                        blank=True,
                        related_name="cross_dept_approvals",
                        to="eims_app.department",
                        verbose_name="协同部门",
                    ),
                ),
                (
                    "level_1_department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="level_1_approvals",
                        to="eims_app.department",
                        verbose_name="一级审批部门",
                    ),
                ),
                (
                    "level_2_department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="level_2_approvals",
                        to="eims_app.department",
                        verbose_name="二级审批部门",
                    ),
                ),
                (
                    "level_3_department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="level_3_approvals",
                        to="eims_app.department",
                        verbose_name="三级审批部门",
                    ),
                ),
            ],
            options={
                "verbose_name": "审批链配置",
                "verbose_name_plural": "审批链管理",
                "ordering": ["business_type", "name"],
            },
        ),
        migrations.CreateModel(
            name="DepartmentRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="是否删除"),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "role_type",
                    models.CharField(
                        choices=[
                            ("manager", "部门经理"),
                            ("deputy", "部门副职"),
                            ("supervisor", "主管"),
                            ("member", "普通成员"),
                            ("assistant", "助理"),
                        ],
                        max_length=20,
                        verbose_name="角色类型",
                    ),
                ),
                (
                    "role_name",
                    models.CharField(
                        help_text="如：工程部经理、技术部主管等",
                        max_length=50,
                        verbose_name="角色名称",
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(
                        default=False,
                        help_text="同一角色类型只能有一个主要负责人",
                        verbose_name="是否主要负责人",
                    ),
                ),
                (
                    "permissions",
                    models.TextField(
                        blank=True,
                        help_text="逗号分隔的权限代码",
                        verbose_name="权限列表",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="department_roles",
                        to="eims_app.department",
                        verbose_name="所属部门",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="department_roles",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "部门角色",
                "verbose_name_plural": "部门角色配置",
            },
        ),
        migrations.AddIndex(
            model_name="department",
            index=models.Index(
                fields=["department_code"], name="eims_app_de_departm_fa6d34_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="department",
            index=models.Index(fields=["status"], name="eims_app_de_status_8615d5_idx"),
        ),
        migrations.AddIndex(
            model_name="departmentrole",
            index=models.Index(
                fields=["department", "role_type"],
                name="eims_app_de_departm_9a6de7_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="departmentrole",
            unique_together={("department", "user", "role_type")},
        ),
    ]
