# Generated by Django 5.2 on 2026-03-21 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eims_app", "0005_department_approvalchain_departmentrole_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="department",
            options={
                "ordering": ["order", "department_code"],
                "verbose_name": "部门",
                "verbose_name_plural": "部门管理",
            },
        ),
        migrations.AlterModelOptions(
            name="filemanage",
            options={
                "ordering": ("-publish_time",),
                "verbose_name": "文件",
                "verbose_name_plural": "文件管理",
            },
        ),
        migrations.RemoveField(
            model_name="filemanage",
            name="upload_time",
        ),
        migrations.AddField(
            model_name="filemanage",
            name="content_summary",
            field=models.TextField(
                blank=True,
                help_text="请输入文件内容摘要",
                null=True,
                verbose_name="内容摘要",
            ),
        ),
        migrations.AddField(
            model_name="filemanage",
            name="file_category",
            field=models.CharField(
                blank=True,
                help_text="请选择文件类别",
                max_length=100,
                null=True,
                verbose_name="文件类别",
            ),
        ),
        migrations.AddField(
            model_name="filemanage",
            name="file_number",
            field=models.CharField(
                blank=True,
                help_text="请输入文件编号",
                max_length=100,
                null=True,
                verbose_name="文件编号",
            ),
        ),
        migrations.AddField(
            model_name="filemanage",
            name="is_deleted",
            field=models.BooleanField(default=False, verbose_name="是否删除"),
        ),
        migrations.AddField(
            model_name="filemanage",
            name="publish_time",
            field=models.DateTimeField(blank=True, null=True, verbose_name="发布时间"),
        ),
        migrations.AddField(
            model_name="filemanage",
            name="remark",
            field=models.TextField(
                blank=True, help_text="请输入备注信息", null=True, verbose_name="备注"
            ),
        ),
        migrations.AddField(
            model_name="filemanage",
            name="update_time",
            field=models.DateTimeField(auto_now=True, verbose_name="更新时间"),
        ),
        migrations.AlterField(
            model_name="filemanage",
            name="uploader",
            field=models.CharField(
                blank=True,
                help_text="系统自动获取",
                max_length=100,
                null=True,
                verbose_name="上传人",
            ),
        ),
    ]
