# Generated by Django 5.2 on 2026-03-21 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eims_app", "0006_alter_department_options_alter_filemanage_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="filemanage",
            name="publish_time",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="发布时间"
            ),
        ),
        migrations.AlterField(
            model_name="filemanage",
            name="update_time",
            field=models.DateTimeField(
                auto_now=True, null=True, verbose_name="更新时间"
            ),
        ),
    ]
