# Generated by Django 4.2.7 on 2026-04-16 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eims_app', '0007_add_cost_sub_modules'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostRemunerationDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_code', models.CharField(db_index=True, max_length=50, verbose_name='项目编号')),
                ('project_name', models.CharField(db_index=True, max_length=200, verbose_name='项目名称')),
                ('calculation_type', models.CharField(choices=[('compilation', '编制项目'), ('review', '审核项目')], default='compilation', max_length=20, verbose_name='计算类型')),
                ('calculation_base', models.CharField(choices=[('total_cost', '工程总造价'), ('reduced_amount', '审减金额')], default='total_cost', max_length=20, verbose_name='计算基准')),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='工程总造价(万元)')),
                ('reduced_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='审减金额(万元)')),
                ('total_remuneration', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='酬劳总额(万元)')),
                ('calculation_formula', models.TextField(blank=True, help_text='例如：工程总造价×0.3%', verbose_name='计算式')),
                ('distribution_status', models.CharField(choices=[('draft', '草稿'), ('confirmed', '已确认'), ('distributed', '已分配')], default='draft', max_length=20, verbose_name='分配状态')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('tenant', models.ForeignKey(blank=True, db_constraint=False, help_text='数据隔离依据', null=True, on_delete=django.db.models.deletion.PROTECT, to='eims_app.tenant', verbose_name='所属公司')),
            ],
            options={
                'verbose_name': '酬劳分配',
                'verbose_name_plural': '酬劳分配管理',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CostRemunerationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name', models.CharField(max_length=50, verbose_name='人员姓名')),
                ('role', models.CharField(choices=[('compiler', '编制人'), ('first_reviewer', '一审人员'), ('second_reviewer', '二审人员'), ('third_reviewer', '三审人员'), ('other', '其他人员')], default='compiler', max_length=20, verbose_name='角色')),
                ('distribution_percentage', models.DecimalField(decimal_places=2, default=0, help_text='例如：40表示40%', max_digits=6, verbose_name='分配比例(%)')),
                ('calculated_amount', models.DecimalField(decimal_places=2, default=0, help_text='系统自动计算：酬劳总额×分配比例', max_digits=12, verbose_name='计算酬劳(万元)')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('distribution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='eims_app.costremunerationdistribution', verbose_name='酬劳分配')),
            ],
            options={
                'verbose_name': '酬劳分配明细',
                'verbose_name_plural': '酬劳分配明细管理',
                'ordering': ['role', 'person_name'],
                'indexes': [models.Index(fields=['distribution', 'person_name'], name='eims_app_co_distrib_aadcb0_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='costremunerationdistribution',
            index=models.Index(fields=['project_code', 'project_name'], name='eims_app_co_project_8412ef_idx'),
        ),
    ]
