# Generated by Django 5.2 on 2026-03-21 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eims_app", "0007_alter_filemanage_publish_time_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="notice",
            name="file_name",
            field=models.CharField(
                blank=True,
                help_text="上传文件的原始名称",
                max_length=255,
                null=True,
                verbose_name="文件名称",
            ),
        ),
        migrations.AddField(
            model_name="notice",
            name="file_size",
            field=models.BigIntegerField(
                blank=True, default=0, null=True, verbose_name="文件大小（字节）"
            ),
        ),
        migrations.AddField(
            model_name="notice",
            name="file_type",
            field=models.CharField(
                blank=True,
                help_text="自动识别文件后缀",
                max_length=50,
                null=True,
                verbose_name="文件类型",
            ),
        ),
    ]
