# Generated by Django 5.2 on 2026-03-21 16:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eims_app", "0008_notice_file_name_notice_file_size_notice_file_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FileAccessPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "permission_type",
                    models.CharField(
                        choices=[
                            ("view", "仅查看"),
                            ("download", "查看 + 下载"),
                            ("upload", "查看 + 下载 + 上传"),
                            ("admin", "完全控制"),
                        ],
                        default="view",
                        max_length=20,
                        verbose_name="权限类型",
                    ),
                ),
                (
                    "can_preview_office",
                    models.BooleanField(
                        default=False,
                        help_text="是否允许使用 Office Online 预览",
                        verbose_name="可否预览 Office 文档",
                    ),
                ),
                (
                    "can_batch_upload",
                    models.BooleanField(
                        default=False,
                        help_text="是否允许一次上传多个文件",
                        verbose_name="可否批量上传",
                    ),
                ),
                (
                    "can_manage_versions",
                    models.BooleanField(
                        default=False,
                        help_text="是否允许上传新版本/删除旧版本",
                        verbose_name="可否管理版本",
                    ),
                ),
                (
                    "apply_to_notices",
                    models.BooleanField(default=True, verbose_name="适用于通知公告"),
                ),
                (
                    "apply_to_file_manage",
                    models.BooleanField(default=True, verbose_name="适用于文件管理"),
                ),
                (
                    "created_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "remark",
                    models.TextField(blank=True, null=True, verbose_name="备注说明"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="file_permissions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "文件访问权限",
                "verbose_name_plural": "文件访问权限",
                "unique_together": {("user",)},
            },
        ),
        migrations.CreateModel(
            name="FileManageVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="file_manage/versions/", verbose_name="文件"
                    ),
                ),
                (
                    "file_name",
                    models.CharField(max_length=255, verbose_name="文件名称"),
                ),
                (
                    "file_size",
                    models.BigIntegerField(default=0, verbose_name="文件大小（字节）"),
                ),
                ("file_type", models.CharField(max_length=50, verbose_name="文件类型")),
                (
                    "version",
                    models.IntegerField(
                        default=1,
                        help_text="文件版本号，从 1 开始",
                        verbose_name="版本号",
                    ),
                ),
                (
                    "is_latest",
                    models.BooleanField(default=True, verbose_name="是否最新版本"),
                ),
                (
                    "uploader",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="上传人"
                    ),
                ),
                (
                    "upload_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="上传时间"),
                ),
                (
                    "change_log",
                    models.TextField(
                        blank=True,
                        help_text="本次更新的变更说明",
                        null=True,
                        verbose_name="变更说明",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="是否删除"),
                ),
                (
                    "file_manage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="eims_app.filemanage",
                        verbose_name="文件",
                    ),
                ),
            ],
            options={
                "verbose_name": "文件版本",
                "verbose_name_plural": "文件版本",
                "ordering": ["-version"],
                "indexes": [
                    models.Index(
                        fields=["file_manage", "-version"],
                        name="eims_app_fi_file_ma_f7111a_idx",
                    ),
                    models.Index(
                        fields=["file_manage", "is_latest"],
                        name="eims_app_fi_file_ma_3098a0_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="NoticeAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="notices/attachments/", verbose_name="文件"
                    ),
                ),
                (
                    "file_name",
                    models.CharField(max_length=255, verbose_name="文件名称"),
                ),
                (
                    "file_size",
                    models.BigIntegerField(default=0, verbose_name="文件大小（字节）"),
                ),
                ("file_type", models.CharField(max_length=50, verbose_name="文件类型")),
                (
                    "version",
                    models.IntegerField(
                        default=1,
                        help_text="文件版本号，从 1 开始",
                        verbose_name="版本号",
                    ),
                ),
                (
                    "is_latest",
                    models.BooleanField(default=True, verbose_name="是否最新版本"),
                ),
                (
                    "upload_person",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="上传人"
                    ),
                ),
                (
                    "upload_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="上传时间"),
                ),
                (
                    "remark",
                    models.TextField(blank=True, null=True, verbose_name="备注说明"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="是否删除"),
                ),
                (
                    "notice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="eims_app.notice",
                        verbose_name="通知",
                    ),
                ),
            ],
            options={
                "verbose_name": "通知附件",
                "verbose_name_plural": "通知附件",
                "ordering": ["-version"],
                "indexes": [
                    models.Index(
                        fields=["notice", "-version"],
                        name="eims_app_no_notice__6d5dde_idx",
                    ),
                    models.Index(
                        fields=["notice", "is_latest"],
                        name="eims_app_no_notice__492aac_idx",
                    ),
                ],
            },
        ),
    ]
