# Generated by Django 4.2.7 on 2026-04-16 04:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eims_app', '0008_add_remuneration_distribution'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='costprojectinfo',
            options={'ordering': ['-created_at'], 'verbose_name': '造价咨询项目', 'verbose_name_plural': '造价咨询项目管理'},
        ),
        migrations.AddField(
            model_name='costpaymentstatus',
            name='approval_status',
            field=models.CharField(db_index=True, default='draft', max_length=20, verbose_name='审批状态'),
        ),
        migrations.AddField(
            model_name='costpaymentstatus',
            name='operator',
            field=models.CharField(blank=True, max_length=50, verbose_name='操作人'),
        ),
        migrations.AddField(
            model_name='costpaymentstatus',
            name='project',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cost_payment_statuses', to='eims_app.costprojectinfo', verbose_name='关联项目'),
        ),
        migrations.AddField(
            model_name='costpaymentstatus',
            name='project_type',
            field=models.CharField(blank=True, max_length=20, verbose_name='项目类型'),
        ),
        migrations.AddField(
            model_name='costprojectarchive',
            name='approval_status',
            field=models.CharField(db_index=True, default='draft', max_length=20, verbose_name='审批状态'),
        ),
        migrations.AddField(
            model_name='costprojectarchive',
            name='operator',
            field=models.CharField(blank=True, max_length=50, verbose_name='操作人'),
        ),
        migrations.AddField(
            model_name='costprojectarchive',
            name='project',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cost_archives', to='eims_app.costprojectinfo', verbose_name='关联项目'),
        ),
        migrations.AddField(
            model_name='costprojectarchive',
            name='project_type',
            field=models.CharField(blank=True, max_length=20, verbose_name='项目类型'),
        ),
        migrations.AddField(
            model_name='costprojectarchive',
            name='submitter_user',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cost_archives_submitted', to=settings.AUTH_USER_MODEL, verbose_name='提交人'),
        ),
        migrations.AddField(
            model_name='costprojectinfo',
            name='approval_department',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cost_project_approvals', to='eims_app.department', verbose_name='审批部门'),
        ),
        migrations.AddField(
            model_name='costprojectinfo',
            name='approval_flow_type',
            field=models.CharField(blank=True, choices=[('user_selected', '用户选择'), ('auto_assigned', '系统指派')], default='auto_assigned', max_length=30, verbose_name='审批流程类型'),
        ),
        migrations.AddField(
            model_name='costprojectinfo',
            name='approval_level',
            field=models.IntegerField(default=1, help_text='1=部门级，2=上级', verbose_name='审批级别'),
        ),
        migrations.AddField(
            model_name='costprojectinfo',
            name='approval_remark',
            field=models.TextField(blank=True, verbose_name='审批意见'),
        ),
        migrations.AddField(
            model_name='costprojectinfo',
            name='approval_status',
            field=models.CharField(choices=[('draft', '草稿'), ('pending_approval', '待审批'), ('approved', '已审批'), ('rejected', '已退回'), ('cancelled', '已撤销')], db_index=True, default='draft', max_length=20, verbose_name='审批状态'),
        ),
        migrations.AddField(
            model_name='costprojectinfo',
            name='approval_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='审批时间'),
        ),
        migrations.AddField(
            model_name='costprojectinfo',
            name='current_approver',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cost_project_approvals', to=settings.AUTH_USER_MODEL, verbose_name='当前审批人'),
        ),
        migrations.AddField(
            model_name='costprojectinfo',
            name='operator',
            field=models.CharField(blank=True, help_text='记录最后操作人', max_length=50, verbose_name='操作人'),
        ),
        migrations.AddField(
            model_name='costprojectinfo',
            name='submit_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='提交审批时间'),
        ),
        migrations.AddField(
            model_name='costremunerationdistribution',
            name='approval_department',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cost_remuneration_approvals', to='eims_app.department', verbose_name='审批部门'),
        ),
        migrations.AddField(
            model_name='costremunerationdistribution',
            name='approval_level',
            field=models.IntegerField(default=1, help_text='1=部门级，2=上级', verbose_name='审批级别'),
        ),
        migrations.AddField(
            model_name='costremunerationdistribution',
            name='approval_remark',
            field=models.TextField(blank=True, verbose_name='审批意见'),
        ),
        migrations.AddField(
            model_name='costremunerationdistribution',
            name='approval_status',
            field=models.CharField(db_index=True, default='draft', max_length=20, verbose_name='审批状态'),
        ),
        migrations.AddField(
            model_name='costremunerationdistribution',
            name='approval_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='审批时间'),
        ),
        migrations.AddField(
            model_name='costremunerationdistribution',
            name='current_approver',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cost_remuneration_approvals', to=settings.AUTH_USER_MODEL, verbose_name='当前审批人'),
        ),
        migrations.AddField(
            model_name='costremunerationdistribution',
            name='operator',
            field=models.CharField(blank=True, max_length=50, verbose_name='操作人'),
        ),
        migrations.AddField(
            model_name='costremunerationdistribution',
            name='project',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cost_remunerations', to='eims_app.costprojectinfo', verbose_name='关联项目'),
        ),
        migrations.AddField(
            model_name='costremunerationdistribution',
            name='project_type',
            field=models.CharField(blank=True, max_length=20, verbose_name='项目类型'),
        ),
        migrations.AddField(
            model_name='costremunerationdistribution',
            name='submit_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='提交审批时间'),
        ),
        migrations.AddField(
            model_name='costremunerationitem',
            name='department',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='关联部门管理模块', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cost_remuneration_items', to='eims_app.department', verbose_name='所属部门'),
        ),
        migrations.AddField(
            model_name='costremunerationitem',
            name='personnel',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='关联人员管理模块', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cost_remuneration_items', to='eims_app.personnel', verbose_name='关联人员'),
        ),
        migrations.AddField(
            model_name='costremunerationitem',
            name='personnel_department',
            field=models.CharField(blank=True, max_length=100, verbose_name='人员部门'),
        ),
        migrations.AddField(
            model_name='costreviewresult',
            name='approval_status',
            field=models.CharField(db_index=True, default='draft', max_length=20, verbose_name='审批状态'),
        ),
        migrations.AddField(
            model_name='costreviewresult',
            name='operator',
            field=models.CharField(blank=True, max_length=50, verbose_name='操作人'),
        ),
        migrations.AddField(
            model_name='costreviewresult',
            name='project',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cost_review_results', to='eims_app.costprojectinfo', verbose_name='关联项目'),
        ),
        migrations.AddField(
            model_name='costreviewresult',
            name='second_reduction',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='二审审减(万元)'),
        ),
        migrations.AddField(
            model_name='costreviewresult',
            name='third_reduction',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='三审审减(万元)'),
        ),
        migrations.AddField(
            model_name='costtaskimplementation',
            name='approval_status',
            field=models.CharField(db_index=True, default='draft', max_length=20, verbose_name='审批状态'),
        ),
        migrations.AddField(
            model_name='costtaskimplementation',
            name='compiler_personnel',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cost_task_implementations_as_compiler', to='eims_app.personnel', verbose_name='编制人员'),
        ),
        migrations.AddField(
            model_name='costtaskimplementation',
            name='first_reviewer_personnel',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cost_task_implementations_as_first_reviewer', to='eims_app.personnel', verbose_name='一审人员'),
        ),
        migrations.AddField(
            model_name='costtaskimplementation',
            name='operator',
            field=models.CharField(blank=True, max_length=50, verbose_name='操作人'),
        ),
        migrations.AddField(
            model_name='costtaskimplementation',
            name='project',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cost_task_implementations', to='eims_app.costprojectinfo', verbose_name='关联项目'),
        ),
        migrations.AddField(
            model_name='costtaskimplementation',
            name='second_reviewer_personnel',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cost_task_implementations_as_second_reviewer', to='eims_app.personnel', verbose_name='二审人员'),
        ),
        migrations.AddField(
            model_name='costtaskimplementation',
            name='third_reviewer_personnel',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cost_task_implementations_as_third_reviewer', to='eims_app.personnel', verbose_name='三审人员'),
        ),
        migrations.AddField(
            model_name='costtaskplan',
            name='approval_status',
            field=models.CharField(choices=[('draft', '草稿'), ('pending_approval', '待审批'), ('approved', '已审批'), ('rejected', '已退回'), ('cancelled', '已撤销')], db_index=True, default='draft', max_length=20, verbose_name='审批状态'),
        ),
        migrations.AddField(
            model_name='costtaskplan',
            name='compiler_personnel',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='关联人员管理模块', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cost_task_plans_as_compiler', to='eims_app.personnel', verbose_name='编制人员'),
        ),
        migrations.AddField(
            model_name='costtaskplan',
            name='current_approver',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cost_task_plan_approvals', to=settings.AUTH_USER_MODEL, verbose_name='当前审批人'),
        ),
        migrations.AddField(
            model_name='costtaskplan',
            name='first_reviewer_department',
            field=models.CharField(blank=True, max_length=100, verbose_name='一审部门'),
        ),
        migrations.AddField(
            model_name='costtaskplan',
            name='first_reviewer_personnel',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cost_task_plans_as_first_reviewer', to='eims_app.personnel', verbose_name='一审人员'),
        ),
        migrations.AddField(
            model_name='costtaskplan',
            name='operator',
            field=models.CharField(blank=True, max_length=50, verbose_name='操作人'),
        ),
        migrations.AddField(
            model_name='costtaskplan',
            name='project',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='选择造价咨询项目', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cost_task_plans', to='eims_app.costprojectinfo', verbose_name='关联项目'),
        ),
        migrations.AddField(
            model_name='costtaskplan',
            name='second_reviewer_department',
            field=models.CharField(blank=True, max_length=100, verbose_name='二审部门'),
        ),
        migrations.AddField(
            model_name='costtaskplan',
            name='second_reviewer_personnel',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cost_task_plans_as_second_reviewer', to='eims_app.personnel', verbose_name='二审人员'),
        ),
        migrations.AddField(
            model_name='costtaskplan',
            name='third_reviewer_department',
            field=models.CharField(blank=True, max_length=100, verbose_name='三审部门'),
        ),
        migrations.AddField(
            model_name='costtaskplan',
            name='third_reviewer_personnel',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cost_task_plans_as_third_reviewer', to='eims_app.personnel', verbose_name='三审人员'),
        ),
        migrations.AlterField(
            model_name='costpaymentstatus',
            name='project_code',
            field=models.CharField(blank=True, db_index=True, max_length=50, verbose_name='项目编号'),
        ),
        migrations.AlterField(
            model_name='costpaymentstatus',
            name='project_name',
            field=models.CharField(blank=True, db_index=True, max_length=200, verbose_name='项目名称'),
        ),
        migrations.AlterField(
            model_name='costpaymentstatus',
            name='tenant',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='eims_app.tenant', verbose_name='所属公司'),
        ),
        migrations.AlterField(
            model_name='costprojectarchive',
            name='project_code',
            field=models.CharField(blank=True, db_index=True, max_length=50, verbose_name='项目编号'),
        ),
        migrations.AlterField(
            model_name='costprojectarchive',
            name='project_name',
            field=models.CharField(blank=True, db_index=True, max_length=200, verbose_name='项目名称'),
        ),
        migrations.AlterField(
            model_name='costprojectarchive',
            name='tenant',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='eims_app.tenant', verbose_name='所属公司'),
        ),
        migrations.AlterField(
            model_name='costremunerationdistribution',
            name='project_code',
            field=models.CharField(blank=True, db_index=True, max_length=50, verbose_name='项目编号'),
        ),
        migrations.AlterField(
            model_name='costremunerationdistribution',
            name='project_name',
            field=models.CharField(blank=True, db_index=True, max_length=200, verbose_name='项目名称'),
        ),
        migrations.AlterField(
            model_name='costremunerationdistribution',
            name='tenant',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='eims_app.tenant', verbose_name='所属公司'),
        ),
        migrations.AlterField(
            model_name='costreviewresult',
            name='project_code',
            field=models.CharField(blank=True, db_index=True, max_length=50, verbose_name='项目编号'),
        ),
        migrations.AlterField(
            model_name='costreviewresult',
            name='project_name',
            field=models.CharField(blank=True, db_index=True, max_length=200, verbose_name='项目名称'),
        ),
        migrations.AlterField(
            model_name='costreviewresult',
            name='project_type',
            field=models.CharField(blank=True, max_length=20, verbose_name='项目类型'),
        ),
        migrations.AlterField(
            model_name='costreviewresult',
            name='tenant',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='eims_app.tenant', verbose_name='所属公司'),
        ),
        migrations.AlterField(
            model_name='costtaskimplementation',
            name='project_code',
            field=models.CharField(blank=True, db_index=True, max_length=50, verbose_name='项目编号'),
        ),
        migrations.AlterField(
            model_name='costtaskimplementation',
            name='project_name',
            field=models.CharField(blank=True, db_index=True, max_length=200, verbose_name='项目名称'),
        ),
        migrations.AlterField(
            model_name='costtaskimplementation',
            name='project_type',
            field=models.CharField(blank=True, max_length=20, verbose_name='项目类型'),
        ),
        migrations.AlterField(
            model_name='costtaskimplementation',
            name='tenant',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='eims_app.tenant', verbose_name='所属公司'),
        ),
        migrations.AlterField(
            model_name='costtaskplan',
            name='project_code',
            field=models.CharField(blank=True, db_index=True, max_length=50, verbose_name='项目编号'),
        ),
        migrations.AlterField(
            model_name='costtaskplan',
            name='project_name',
            field=models.CharField(blank=True, db_index=True, max_length=200, verbose_name='项目名称'),
        ),
        migrations.AlterField(
            model_name='costtaskplan',
            name='project_type',
            field=models.CharField(blank=True, choices=[('budget', '预算'), ('settlement', '结算'), ('audit', '审核'), ('other', '其他')], default='budget', max_length=20, verbose_name='项目类型'),
        ),
        migrations.AlterField(
            model_name='costtaskplan',
            name='tenant',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='eims_app.tenant', verbose_name='所属公司'),
        ),
        migrations.AddIndex(
            model_name='costprojectinfo',
            index=models.Index(fields=['approval_status'], name='eims_app_co_approva_c9f17d_idx'),
        ),
        migrations.AddIndex(
            model_name='costtaskplan',
            index=models.Index(fields=['approval_status'], name='eims_app_co_approva_895fee_idx'),
        ),
    ]
