# Generated by Django 5.2 on 2026-03-22 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eims_app", "0009_fileaccesspermission_filemanageversion_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "employee_code",
                    models.CharField(
                        help_text="请输入唯一的员工编号",
                        max_length=50,
                        unique=True,
                        verbose_name="员工编号",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="请输入人员姓名", max_length=50, verbose_name="姓名"
                    ),
                ),
                (
                    "gender",
                    models.SmallIntegerField(
                        choices=[(0, "男"), (1, "女"), (2, "其他")],
                        default=0,
                        help_text="请选择人员性别",
                        verbose_name="性别",
                    ),
                ),
                (
                    "id_card",
                    models.CharField(
                        help_text="18 位身份证号码",
                        max_length=18,
                        verbose_name="身份证号",
                    ),
                ),
                (
                    "native_place",
                    models.CharField(
                        blank=True,
                        help_text="填写籍贯",
                        max_length=100,
                        verbose_name="籍贯",
                    ),
                ),
                (
                    "ethnic",
                    models.CharField(
                        choices=[
                            ("han", "汉族"),
                            ("hui", "回族"),
                            ("man", "满族"),
                            ("mongol", "蒙古族"),
                            ("tibetan", "藏族"),
                            ("uyghur", "维吾尔族"),
                            ("other", "其他"),
                        ],
                        default="han",
                        help_text="选择民族",
                        max_length=20,
                        verbose_name="民族",
                    ),
                ),
                (
                    "education",
                    models.CharField(
                        choices=[
                            ("primary", "小学"),
                            ("junior", "初中"),
                            ("senior", "高中"),
                            ("college", "大专"),
                            ("bachelor", "本科"),
                            ("master", "硕士"),
                            ("doctor", "博士"),
                        ],
                        default="bachelor",
                        help_text="选择最高学历",
                        max_length=20,
                        verbose_name="学历",
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True,
                        help_text="填写详细住址",
                        max_length=200,
                        verbose_name="住址",
                    ),
                ),
                (
                    "home_phone",
                    models.CharField(
                        blank=True,
                        help_text="家庭固定电话",
                        max_length=20,
                        verbose_name="固定电话",
                    ),
                ),
                (
                    "mobile",
                    models.CharField(
                        help_text="请输入手机号码", max_length=20, verbose_name="手机号"
                    ),
                ),
                (
                    "emergency_contact",
                    models.CharField(
                        blank=True,
                        help_text="填写应急联系人姓名",
                        max_length=50,
                        verbose_name="应急联系人",
                    ),
                ),
                (
                    "emergency_phone",
                    models.CharField(
                        blank=True,
                        help_text="填写应急联系电话",
                        max_length=20,
                        verbose_name="应急电话",
                    ),
                ),
                (
                    "wechat",
                    models.CharField(
                        blank=True,
                        help_text="填写微信号",
                        max_length=50,
                        verbose_name="微信",
                    ),
                ),
                (
                    "admin_position",
                    models.CharField(
                        blank=True,
                        help_text="填写行政职务",
                        max_length=100,
                        verbose_name="行政职务",
                    ),
                ),
                (
                    "tech_position",
                    models.CharField(
                        blank=True,
                        help_text="填写技术职务",
                        max_length=100,
                        verbose_name="技术职务",
                    ),
                ),
                (
                    "professional_qualification",
                    models.CharField(
                        blank=True,
                        help_text="填写执业资格证书名称",
                        max_length=200,
                        verbose_name="执业资格",
                    ),
                ),
                (
                    "professional_title",
                    models.CharField(
                        blank=True,
                        help_text="填写专业技术职称",
                        max_length=100,
                        verbose_name="职称",
                    ),
                ),
                (
                    "job_qualification",
                    models.CharField(
                        blank=True,
                        help_text="填写任职资格",
                        max_length=200,
                        verbose_name="任职资格",
                    ),
                ),
                (
                    "entry_time",
                    models.DateField(
                        blank=True,
                        help_text="选择入职时间",
                        null=True,
                        verbose_name="入职时间",
                    ),
                ),
                (
                    "leave_time",
                    models.DateField(
                        blank=True,
                        help_text="选择离职时间",
                        null=True,
                        verbose_name="离职时间",
                    ),
                ),
                (
                    "operator",
                    models.CharField(blank=True, max_length=100, verbose_name="操作人"),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="是否删除"),
                ),
                (
                    "remark",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="可选，输入备注信息",
                        verbose_name="备注",
                    ),
                ),
            ],
            options={
                "verbose_name": "员工信息",
                "verbose_name_plural": "员工信息管理",
                "ordering": ("-entry_time",),
            },
        ),
        migrations.RemoveField(
            model_name="personnel",
            name="address",
        ),
        migrations.RemoveField(
            model_name="personnel",
            name="admin_position",
        ),
        migrations.RemoveField(
            model_name="personnel",
            name="education",
        ),
        migrations.RemoveField(
            model_name="personnel",
            name="emergency_contact",
        ),
        migrations.RemoveField(
            model_name="personnel",
            name="emergency_phone",
        ),
        migrations.RemoveField(
            model_name="personnel",
            name="ethnic",
        ),
        migrations.RemoveField(
            model_name="personnel",
            name="home_phone",
        ),
        migrations.RemoveField(
            model_name="personnel",
            name="id_card",
        ),
        migrations.RemoveField(
            model_name="personnel",
            name="job_qualification",
        ),
        migrations.RemoveField(
            model_name="personnel",
            name="mobile",
        ),
        migrations.RemoveField(
            model_name="personnel",
            name="native_place",
        ),
        migrations.RemoveField(
            model_name="personnel",
            name="professional_qualification",
        ),
        migrations.RemoveField(
            model_name="personnel",
            name="professional_title",
        ),
        migrations.RemoveField(
            model_name="personnel",
            name="tech_position",
        ),
        migrations.RemoveField(
            model_name="personnel",
            name="wechat",
        ),
        migrations.AlterField(
            model_name="personnel",
            name="entry_time",
            field=models.DateField(
                blank=True, help_text="选择入岗时间", null=True, verbose_name="入岗时间"
            ),
        ),
        migrations.AlterField(
            model_name="personnel",
            name="gender",
            field=models.SmallIntegerField(
                choices=[(0, "男"), (1, "女"), (2, "其他")],
                default=0,
                verbose_name="性别",
            ),
        ),
        migrations.AlterField(
            model_name="personnel",
            name="leave_time",
            field=models.DateField(
                blank=True, help_text="选择离岗时间", null=True, verbose_name="离岗时间"
            ),
        ),
        migrations.AlterField(
            model_name="personnel",
            name="personnel_code",
            field=models.CharField(
                db_index=True, default="", max_length=50, verbose_name="人员编号"
            ),
        ),
        migrations.AddField(
            model_name="personnel",
            name="employee",
            field=models.ForeignKey(
                blank=True,
                help_text="选择员工",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="project_assignments",
                to="eims_app.employee",
                verbose_name="员工",
            ),
        ),
    ]
