# Generated by Django 4.2.7 on 2026-04-16 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eims_app', '0009_cost_sub_modules_fk_refactor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costprojectinfo',
            name='approval_level',
            field=models.IntegerField(blank=True, default=1, help_text='1=部门级，2=上级', verbose_name='审批级别'),
        ),
        migrations.AlterField(
            model_name='costprojectinfo',
            name='approval_status',
            field=models.CharField(blank=True, choices=[('draft', '草稿'), ('pending_approval', '待审批'), ('approved', '已审批'), ('rejected', '已退回'), ('cancelled', '已撤销')], db_index=True, default='draft', max_length=20, verbose_name='审批状态'),
        ),
        migrations.AlterField(
            model_name='costprojectinfo',
            name='compilation_category',
            field=models.CharField(blank=True, choices=[('civil', '土建'), ('install', '安装'), ('municipal', '市政'), ('decoration', '装饰'), ('other', '其他')], default='civil', max_length=20, verbose_name='编制类别'),
        ),
        migrations.AlterField(
            model_name='costprojectinfo',
            name='fee_settlement',
            field=models.CharField(blank=True, choices=[('settled', '已结清'), ('unsettled', '未结清'), ('partial', '部分结清')], default='unsettled', max_length=20, verbose_name='费用结清'),
        ),
        migrations.AlterField(
            model_name='costprojectinfo',
            name='planned_duration',
            field=models.IntegerField(blank=True, default=0, verbose_name='计划工期(天)'),
        ),
        migrations.AlterField(
            model_name='costprojectinfo',
            name='project_status',
            field=models.CharField(blank=True, choices=[('not_started', '未开始'), ('in_progress', '进行中'), ('completed', '已完成'), ('suspended', '已暂停')], default='not_started', max_length=20, verbose_name='项目状态'),
        ),
        migrations.AlterField(
            model_name='costprojectinfo',
            name='project_type',
            field=models.CharField(blank=True, choices=[('budget', '预算'), ('settlement', '结算'), ('audit', '审核'), ('other', '其他')], default='budget', max_length=20, verbose_name='项目类型'),
        ),
        migrations.AlterField(
            model_name='costprojectinfo',
            name='result_confirm',
            field=models.CharField(blank=True, choices=[('confirmed', '已确认'), ('unconfirmed', '未确认'), ('pending', '待确认')], default='unconfirmed', max_length=20, verbose_name='结果确认'),
        ),
        migrations.AlterField(
            model_name='costprojectinfo',
            name='review_category',
            field=models.CharField(blank=True, choices=[('initial', '初审'), ('intermediate', '中审'), ('final', '终审')], default='initial', max_length=20, verbose_name='审核类别'),
        ),
    ]
