# Generated by Django 5.2 on 2026-03-22 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eims_app", "0010_employee_remove_personnel_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="personnelallocation",
            name="allocation_department",
            field=models.CharField(
                blank=True,
                help_text="填写在新项目的部门",
                max_length=100,
                verbose_name="分配部门",
            ),
        ),
        migrations.AlterField(
            model_name="personnel",
            name="project",
            field=models.ForeignKey(
                blank=True,
                help_text="选择当前主要归属项目（可选）",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="main_personnel",
                to="eims_app.project",
                verbose_name="主要项目",
            ),
        ),
    ]
