# Generated by Django 5.2 on 2026-03-22 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eims_app", "0011_personnelallocation_allocation_department_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="monthlyreport",
            name="next_month_plan",
        ),
        migrations.RemoveField(
            model_name="monthlyreport",
            name="payment_request",
        ),
        migrations.AddField(
            model_name="monthlyreport",
            name="current_cumulative_output",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="截止到本月的累计产值（自动计算）",
                max_digits=15,
                verbose_name="本月累计产值 (万元)",
            ),
        ),
        migrations.AddField(
            model_name="monthlyreport",
            name="current_cumulative_payment",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="截止到本月的累计回款（自动计算）",
                max_digits=15,
                verbose_name="本月累计回款 (元)",
            ),
        ),
        migrations.AddField(
            model_name="monthlyreport",
            name="current_payment_request",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="本月正在申请的款项金额",
                max_digits=15,
                verbose_name="本月正在请款金额 (元)",
            ),
        ),
        migrations.AddField(
            model_name="monthlyreport",
            name="last_month_cumulative_output",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="截止到上月的累计产值",
                max_digits=15,
                verbose_name="上月累计产值 (万元)",
            ),
        ),
        migrations.AddField(
            model_name="monthlyreport",
            name="last_month_cumulative_payment",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="截止到上月的累计回款",
                max_digits=15,
                verbose_name="上月累计回款 (元)",
            ),
        ),
        migrations.AddField(
            model_name="monthlyreport",
            name="next_month_assistance",
            field=models.TextField(
                blank=True,
                default="",
                help_text="需要公司或领导协助的事项",
                verbose_name="需要的协助",
            ),
        ),
        migrations.AddField(
            model_name="monthlyreport",
            name="next_month_plan_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="计划下月申请的款项金额",
                max_digits=15,
                verbose_name="下月请款金额 (元)",
            ),
        ),
        migrations.AddField(
            model_name="monthlyreport",
            name="next_month_plan_detail",
            field=models.TextField(
                blank=True,
                default="",
                help_text="详细的请款计划和安排",
                verbose_name="具体请款计划",
            ),
        ),
        migrations.AddField(
            model_name="monthlyreport",
            name="payment_issues",
            field=models.TextField(
                blank=True,
                default="",
                help_text="需要协调的问题和建议",
                verbose_name="问题及建议",
            ),
        ),
        migrations.AddField(
            model_name="monthlyreport",
            name="payment_progress",
            field=models.CharField(
                blank=True,
                default="",
                help_text="如：已提交申请/审批中/已到账",
                max_length=200,
                verbose_name="本月请款进度",
            ),
        ),
    ]
