# Generated by Django 4.2.7 on 2026-04-16 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eims_app', '0011_create_cost_unified_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costprojectunified',
            name='project_type',
            field=models.CharField(blank=True, choices=[('budget_compilation', '预算编制'), ('settlement_compilation', '结算编制'), ('budget_review', '预算审核'), ('settlement_review', '结算审核'), ('other', '其他')], default='budget_compilation', max_length=30, verbose_name='项目类型'),
        ),
    ]
