# Generated by Django 5.2 on 2026-03-22 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eims_app", "0012_remove_monthlyreport_next_month_plan_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="monthlyreport",
            name="report_month",
            field=models.CharField(
                help_text="格式：YYYY-MM", max_length=7, verbose_name="填报月份"
            ),
        ),
    ]
