# Generated by Django 4.2.7 on 2026-04-16 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eims_app', '0012_alter_costprojectunified_project_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='costprojectunified',
            name='project_manager_personnel',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cost_unified_as_manager', to='eims_app.personnel', verbose_name='项目负责人'),
        ),
    ]
