# Generated by Django 4.2.7 on 2026-04-16 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eims_app', '0013_costprojectunified_project_manager_personnel'),
    ]

    operations = [
        migrations.AddField(
            model_name='costprojectunified',
            name='completion_time',
            field=models.DateField(blank=True, null=True, verbose_name='完成时间'),
        ),
    ]
