# Generated by Django 5.2 on 2026-03-24 10:42

import eims_app.models.model_project_detail
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eims_app", "0013_alter_monthlyreport_report_month"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="project_manager",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="现场负责人"
            ),
        ),
        migrations.CreateModel(
            name="ProjectDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "contract_category",
                    models.CharField(
                        choices=[
                            ("engineering_supervision", "工程监理"),
                            ("cost_consulting", "造价咨询"),
                            ("testing", "检测"),
                            ("whole_process_consulting", "全过程咨询"),
                        ],
                        default="engineering_supervision",
                        max_length=30,
                        verbose_name="合同类别",
                    ),
                ),
                (
                    "monthly_report_required",
                    models.BooleanField(
                        default=True,
                        help_text="是否需要提交月报",
                        verbose_name="项目月报",
                    ),
                ),
                (
                    "project_code",
                    models.CharField(
                        db_index=True,
                        max_length=50,
                        unique=True,
                        verbose_name="项目编号",
                    ),
                ),
                (
                    "contract_code",
                    models.CharField(
                        db_index=True, max_length=50, verbose_name="合同编号"
                    ),
                ),
                (
                    "project_name",
                    models.CharField(
                        db_index=True, max_length=200, verbose_name="项目名称"
                    ),
                ),
                (
                    "project_status",
                    models.CharField(
                        choices=[
                            ("not_started", "未开工"),
                            ("under_construction", "在施工"),
                            ("stopped", "在停工"),
                            ("completed", "已完工"),
                        ],
                        default="not_started",
                        max_length=20,
                        verbose_name="项目状态",
                    ),
                ),
                (
                    "contract_status",
                    models.CharField(
                        choices=[
                            ("pending_review", "待审核"),
                            ("executing", "在执行"),
                            ("terminated", "已终止"),
                            ("released", "已解除"),
                        ],
                        default="pending_review",
                        max_length=20,
                        verbose_name="合同状态",
                    ),
                ),
                (
                    "settlement_status",
                    models.CharField(
                        choices=[("unsettled", "未结算"), ("settled", "已结算")],
                        default="unsettled",
                        max_length=20,
                        verbose_name="结算情况",
                    ),
                ),
                (
                    "contract_party_a",
                    models.CharField(max_length=200, verbose_name="合同甲方"),
                ),
                (
                    "contract_party_b",
                    models.CharField(max_length=200, verbose_name="合同乙方"),
                ),
                ("signing_date", models.DateField(verbose_name="签订日期")),
                (
                    "contract_text",
                    models.FileField(
                        blank=True,
                        upload_to=eims_app.models.model_project_detail.ProjectDetail.contract_text_upload_path,
                        verbose_name="合同文本",
                    ),
                ),
                (
                    "contract_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="合同总价 (元)"
                    ),
                ),
                (
                    "payment_agreement",
                    models.TextField(blank=True, verbose_name="付款约定"),
                ),
                (
                    "cumulative_payment",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="累计回款",
                    ),
                ),
                (
                    "contract_balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="合同余款",
                    ),
                ),
                (
                    "project_scale",
                    models.CharField(
                        blank=True,
                        help_text="如：建筑面积 5 万㎡/道路长度 10km",
                        max_length=200,
                        verbose_name="项目规模",
                    ),
                ),
                (
                    "project_investment",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                        verbose_name="项目总投资 (万元)",
                    ),
                ),
                (
                    "project_address",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="项目地址"
                    ),
                ),
                (
                    "agreed_staffing",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="约定人员配备"
                    ),
                ),
                (
                    "service_period",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="服务周期"
                    ),
                ),
                (
                    "service_deadline",
                    models.DateField(
                        blank=True, null=True, verbose_name="服务到期日期"
                    ),
                ),
                (
                    "extension_agreement",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="延期约定"
                    ),
                ),
                (
                    "actual_extension_status",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="实际延期情况"
                    ),
                ),
                (
                    "construction_permit_status",
                    models.CharField(
                        choices=[("completed", "已完成"), ("incomplete", "未完成")],
                        default="incomplete",
                        max_length=20,
                        verbose_name="报建情况",
                    ),
                ),
                (
                    "construction_permit",
                    models.FileField(
                        blank=True,
                        upload_to=eims_app.models.model_project_detail.ProjectDetail.construction_permit_upload_path,
                        verbose_name="施工许可证",
                    ),
                ),
                (
                    "entry_notice",
                    models.CharField(
                        choices=[("yes", "有"), ("no", "无")],
                        default="no",
                        max_length=10,
                        verbose_name="进场通知",
                    ),
                ),
                (
                    "entry_notice_document",
                    models.FileField(
                        blank=True,
                        upload_to=eims_app.models.model_project_detail.ProjectDetail.entry_notice_upload_path,
                        verbose_name="进场通知书",
                    ),
                ),
                (
                    "entry_time",
                    models.DateField(blank=True, null=True, verbose_name="进场时间"),
                ),
                (
                    "planned_start_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="计划开工日期"
                    ),
                ),
                (
                    "actual_start_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="实际开工日期"
                    ),
                ),
                (
                    "estimated_completion_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="预计竣工日期"
                    ),
                ),
                (
                    "project_director",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=50,
                        verbose_name="项目总监",
                    ),
                ),
                (
                    "project_manager",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=50,
                        verbose_name="现场负责人",
                    ),
                ),
                (
                    "contact_phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="联系电话"
                    ),
                ),
                ("remark", models.TextField(blank=True, verbose_name="备注")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "监理项目信息",
                "verbose_name_plural": "监理项目信息管理",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["project_code", "project_name"],
                        name="eims_app_pr_project_f94850_idx",
                    ),
                    models.Index(
                        fields=["contract_code"], name="eims_app_pr_contrac_195b86_idx"
                    ),
                    models.Index(
                        fields=["project_status", "contract_status"],
                        name="eims_app_pr_project_e19340_idx",
                    ),
                    models.Index(
                        fields=["contract_category"],
                        name="eims_app_pr_contrac_23003e_idx",
                    ),
                ],
            },
        ),
    ]
