# Generated by Django 5.2 on 2026-03-24 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eims_app", "0014_alter_project_project_manager_projectdetail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inspection",
            name="project",
            field=models.ForeignKey(
                help_text="请选择关联的项目",
                on_delete=django.db.models.deletion.CASCADE,
                to="eims_app.projectdetail",
                verbose_name="关联项目",
            ),
        ),
        migrations.AlterField(
            model_name="monthlyreport",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="eims_app.projectdetail",
                verbose_name="填报项目",
            ),
        ),
        migrations.AlterField(
            model_name="outputpayment",
            name="project",
            field=models.ForeignKey(
                blank=True,
                help_text="选择关联的项目",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="eims_app.projectdetail",
                verbose_name="关联项目",
            ),
        ),
        migrations.AlterField(
            model_name="personnel",
            name="project",
            field=models.ForeignKey(
                blank=True,
                help_text="选择当前主要归属项目（可选）",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="main_personnel",
                to="eims_app.projectdetail",
                verbose_name="主要项目",
            ),
        ),
        migrations.AlterField(
            model_name="personnelallocation",
            name="from_project",
            field=models.ForeignKey(
                blank=True,
                help_text="选择原项目",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="from_projects",
                to="eims_app.projectdetail",
                verbose_name="原项目",
            ),
        ),
        migrations.AlterField(
            model_name="personnelallocation",
            name="to_project",
            field=models.ForeignKey(
                help_text="选择分配到的项目",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="to_projects",
                to="eims_app.projectdetail",
                verbose_name="分配项目",
            ),
        ),
        migrations.AlterField(
            model_name="projectdynamic",
            name="project",
            field=models.ForeignKey(
                blank=True,
                help_text="选择关联的项目",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="eims_app.projectdetail",
                verbose_name="关联项目",
            ),
        ),
        migrations.AlterField(
            model_name="projectreporter",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="eims_app.projectdetail",
                verbose_name="关联项目",
            ),
        ),
        migrations.AlterField(
            model_name="projectrole",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="eims_app.projectdetail",
                verbose_name="项目",
            ),
        ),
    ]
