# Generated by Django 4.2.7 on 2026-04-16 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eims_app', '0014_costprojectunified_completion_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costprojectunified',
            name='approved_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, verbose_name='审定金额(万元)'),
        ),
        migrations.AlterField(
            model_name='costprojectunified',
            name='compilation_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, verbose_name='编制金额(万元)'),
        ),
        migrations.AlterField(
            model_name='costprojectunified',
            name='reduced_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, verbose_name='审减金额(万元)'),
        ),
        migrations.AlterField(
            model_name='costprojectunified',
            name='submission_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, verbose_name='送审金额(万元)'),
        ),
    ]
