# Generated by Django 5.2 on 2026-03-24 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "eims_app",
            "0015_alter_inspection_project_alter_monthlyreport_project_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectdetail",
            name="signing_date",
            field=models.DateField(blank=True, null=True, verbose_name="签订日期"),
        ),
    ]
