# Generated by Django 5.2 on 2026-03-25 08:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eims_app", "0016_alter_projectdetail_signing_date"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ContractApproval",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="审批标题")),
                (
                    "contract_name",
                    models.CharField(max_length=200, verbose_name="合同名称"),
                ),
                (
                    "contract_category",
                    models.CharField(
                        choices=[
                            ("engineering_supervision", "工程监理"),
                            ("cost_consulting", "造价咨询"),
                            ("testing", "工程检测"),
                            ("whole_process_consulting", "全过程咨询"),
                        ],
                        max_length=50,
                        verbose_name="合同类别",
                    ),
                ),
                (
                    "contract_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                        verbose_name="合同金额",
                    ),
                ),
                (
                    "party_a",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="合同甲方"
                    ),
                ),
                ("party_b", models.CharField(max_length=200, verbose_name="合同乙方")),
                (
                    "service_period",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="服务周期"
                    ),
                ),
                (
                    "service_deadline",
                    models.DateField(
                        blank=True, null=True, verbose_name="服务到期时间"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "草稿"),
                            ("pending", "待审核"),
                            ("reviewing", "审核中"),
                            ("approved", "已通过"),
                            ("rejected", "已退回"),
                            ("cancelled", "已撤销"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="审批状态",
                    ),
                ),
                (
                    "approval_result",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("pending", "待签订"),
                            ("signed", "已签订"),
                            ("rejected", "审批未通过"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="审批结果",
                    ),
                ),
                ("remark", models.TextField(blank=True, verbose_name="备注")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="提交时间"
                    ),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="审批通过时间"
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "applicant",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="contract_approvals",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="申请人",
                    ),
                ),
                (
                    "current_approver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="contract_approvals_to_handle",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="当前审批人",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="contract_approvals",
                        to="eims_app.department",
                        verbose_name="申请部门",
                    ),
                ),
                (
                    "generated_contract",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="contract_approval_source",
                        to="eims_app.projectdetail",
                        verbose_name="生成的合同台账",
                    ),
                ),
            ],
            options={
                "verbose_name": "合同审批",
                "verbose_name_plural": "合同审批",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ContractApprovalRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("submit", "提交"),
                            ("approve", "同意"),
                            ("reject", "退回"),
                            ("cancel", "撤销"),
                            ("comment", "评论"),
                        ],
                        max_length=20,
                        verbose_name="操作类型",
                    ),
                ),
                ("comment", models.TextField(blank=True, verbose_name="审批意见")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="操作时间"),
                ),
                (
                    "approval",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approval_records",
                        to="eims_app.contractapproval",
                        verbose_name="所属审批",
                    ),
                ),
                (
                    "operator",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="操作人",
                    ),
                ),
            ],
            options={
                "verbose_name": "合同审批记录",
                "verbose_name_plural": "合同审批记录",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="ContractAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="contract_approvals/%Y/%m/", verbose_name="上传文件"
                    ),
                ),
                (
                    "file_type",
                    models.CharField(
                        choices=[
                            ("contract", "合同文件"),
                            ("attachment", "附件材料"),
                            ("other", "其他资料"),
                        ],
                        default="contract",
                        max_length=20,
                        verbose_name="文件类型",
                    ),
                ),
                ("file_name", models.CharField(max_length=255, verbose_name="文件名")),
                (
                    "file_size",
                    models.IntegerField(default=0, verbose_name="文件大小 (字节)"),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="上传时间"),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "approval",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="eims_app.contractapproval",
                        verbose_name="所属审批",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="上传人",
                    ),
                ),
            ],
            options={
                "verbose_name": "合同附件",
                "verbose_name_plural": "合同附件",
                "ordering": ["-uploaded_at"],
            },
        ),
    ]
