# Generated by Django 4.2.7 on 2026-04-18 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eims_app', '0016_alter_costprojectunified_approved_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costprojectunified',
            name='compilation_category',
            field=models.CharField(blank=True, max_length=50, verbose_name='专业'),
        ),
    ]
