# Generated by Django 5.2 on 2026-03-25 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eims_app", "0017_contractapproval_contractapprovalrecord_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contractapproval",
            name="service_period",
        ),
        migrations.RemoveField(
            model_name="projectdetail",
            name="service_period",
        ),
        migrations.AddField(
            model_name="contractapproval",
            name="service_period_months",
            field=models.IntegerField(
                default=0, help_text="以月为单位", verbose_name="服务周期 (月)"
            ),
        ),
        migrations.AddField(
            model_name="contractapproval",
            name="service_start_date",
            field=models.DateField(blank=True, null=True, verbose_name="服务开始时间"),
        ),
        migrations.AddField(
            model_name="projectdetail",
            name="service_period_months",
            field=models.IntegerField(
                default=0, help_text="以月为单位", verbose_name="服务周期 (月)"
            ),
        ),
        migrations.AddField(
            model_name="projectdetail",
            name="service_start_date",
            field=models.DateField(blank=True, null=True, verbose_name="服务开始时间"),
        ),
    ]
