# Generated by Django 4.2.7 on 2026-04-18 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eims_app', '0017_alter_costprojectunified_compilation_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costprojectunified',
            name='review_category',
            field=models.CharField(blank=True, choices=[('initial', '初审'), ('intermediate', '中审'), ('final', '终审')], default='', max_length=20, verbose_name='审核类别'),
        ),
    ]
