# Generated by Django 5.2 on 2026-03-25 10:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eims_app", "0018_remove_contractapproval_service_period_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="contractapproval",
            name="approval_flow_type",
            field=models.CharField(
                choices=[
                    ("user_selected", "由我选择审批人"),
                    ("system_assigned", "由系统自动指派"),
                ],
                default="system_assigned",
                max_length=20,
                verbose_name="审批流程类型",
            ),
        ),
        migrations.AddField(
            model_name="contractapproval",
            name="approval_level",
            field=models.IntegerField(
                default=1, help_text="1=部门级，2=上级", verbose_name="当前审批级别"
            ),
        ),
        migrations.AddField(
            model_name="contractapproval",
            name="auto_assigned_approver",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="auto_assigned_contract_approvals",
                to=settings.AUTH_USER_MODEL,
                verbose_name="系统指派的审批人",
            ),
        ),
        migrations.AddField(
            model_name="contractapproval",
            name="max_approval_level",
            field=models.IntegerField(
                default=2, help_text="默认 2 级审批", verbose_name="最大审批级别"
            ),
        ),
        migrations.AddField(
            model_name="contractapproval",
            name="selected_approver",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="selected_contract_approvals",
                to=settings.AUTH_USER_MODEL,
                verbose_name="选择的审批人",
            ),
        ),
        migrations.AddField(
            model_name="contractapproval",
            name="selected_department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="selected_contract_approvals",
                to="eims_app.department",
                verbose_name="选择的审批部门",
            ),
        ),
        migrations.CreateModel(
            name="ApprovalFlowConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "flow_type",
                    models.CharField(
                        choices=[
                            ("contract_approval", "合同审批"),
                            ("project_approval", "项目审批"),
                            ("expense_approval", "费用审批"),
                        ],
                        max_length=30,
                        verbose_name="流程类型",
                    ),
                ),
                (
                    "approval_level",
                    models.IntegerField(
                        default=1, help_text="1=部门级，2=上级", verbose_name="审批级别"
                    ),
                ),
                (
                    "approver_role",
                    models.CharField(
                        choices=[
                            ("department_manager", "部门主管"),
                            ("senior_leader", "上级领导"),
                            ("finance_manager", "财务负责人"),
                            ("general_manager", "总经理"),
                        ],
                        max_length=30,
                        verbose_name="审批人角色",
                    ),
                ),
                (
                    "priority",
                    models.IntegerField(
                        default=100,
                        help_text="数字越小优先级越高",
                        verbose_name="优先级",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否启用"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        help_text="为空表示适用于所有部门",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="eims_app.department",
                        verbose_name="适用部门",
                    ),
                ),
            ],
            options={
                "verbose_name": "审批流程配置",
                "verbose_name_plural": "审批流程配置",
                "ordering": ["flow_type", "priority", "approval_level"],
                "unique_together": {("flow_type", "department", "approval_level")},
            },
        ),
        migrations.CreateModel(
            name="DepartmentManager",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("department_manager", "部门主管"),
                            ("senior_leader", "上级领导"),
                            ("finance_manager", "财务负责人"),
                            ("general_manager", "总经理"),
                        ],
                        max_length=30,
                        verbose_name="角色",
                    ),
                ),
                (
                    "approval_level",
                    models.IntegerField(
                        default=1, help_text="1=部门级，2=上级", verbose_name="审批级别"
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(
                        default=False,
                        help_text="同角色中优先匹配",
                        verbose_name="是否主要责任人",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否有效"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dept_managers",
                        to="eims_app.department",
                        verbose_name="部门",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="managed_depts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="管理人员",
                    ),
                ),
            ],
            options={
                "verbose_name": "部门主管",
                "verbose_name_plural": "部门主管",
                "ordering": ["department", "approval_level", "is_primary"],
                "unique_together": {("department", "user", "role")},
            },
        ),
    ]
