# Generated by Django 4.2.7 on 2026-04-18 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eims_app', '0018_alter_costprojectunified_review_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='project_code_prefix',
            field=models.CharField(blank=True, default='', help_text='新建项目编号的默认前缀，如：JCD、DC、SC', max_length=10, verbose_name='项目编号前缀'),
        ),
    ]
