# Generated by Django 5.2 on 2026-03-25 10:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eims_app", "0019_contractapproval_approval_flow_type_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="contractapproval",
            name="initiation_time",
            field=models.DateTimeField(
                blank=True,
                help_text="审批流程的初始提交时间",
                null=True,
                verbose_name="发起时间",
            ),
        ),
        migrations.AddField(
            model_name="contractapproval",
            name="initiator",
            field=models.ForeignKey(
                blank=True,
                help_text="审批流程的发起人",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="initiated_contract_approvals",
                to=settings.AUTH_USER_MODEL,
                verbose_name="发起人",
            ),
        ),
    ]
