# Generated by Django 4.2.7 on 2026-04-19 22:34

from django.db import migrations, models
import eims_app.models.model_cost_unified


class Migration(migrations.Migration):

    dependencies = [
        ('eims_app', '0019_tenant_project_code_prefix'),
    ]

    operations = [
        migrations.AddField(
            model_name='costprojectunified',
            name='archive_audit_report',
            field=models.FileField(blank=True, upload_to=eims_app.models.model_cost_unified.CostProjectUnified.archive_audit_report_upload_path, verbose_name='存档-审核报告'),
        ),
        migrations.AddField(
            model_name='costprojectunified',
            name='archive_audit_report_type',
            field=models.CharField(blank=True, max_length=50, verbose_name='存档-报告附件类型'),
        ),
        migrations.AddField(
            model_name='costprojectunified',
            name='archive_inspection_record',
            field=models.FileField(blank=True, upload_to=eims_app.models.model_cost_unified.CostProjectUnified.archive_inspection_record_upload_path, verbose_name='存档-勘察记录'),
        ),
        migrations.AddField(
            model_name='costprojectunified',
            name='archive_inspection_record_type',
            field=models.CharField(blank=True, max_length=50, verbose_name='存档-勘察附件类型'),
        ),
        migrations.AddField(
            model_name='costprojectunified',
            name='archive_other_document',
            field=models.FileField(blank=True, upload_to=eims_app.models.model_cost_unified.CostProjectUnified.archive_other_document_upload_path, verbose_name='存档-其他文件'),
        ),
        migrations.AddField(
            model_name='costprojectunified',
            name='archive_other_document_type',
            field=models.CharField(blank=True, max_length=50, verbose_name='存档-其他附件类型'),
        ),
        migrations.AddField(
            model_name='costprojectunified',
            name='archive_process_material',
            field=models.FileField(blank=True, upload_to=eims_app.models.model_cost_unified.CostProjectUnified.archive_process_material_upload_path, verbose_name='存档-过程资料'),
        ),
        migrations.AddField(
            model_name='costprojectunified',
            name='archive_process_material_type',
            field=models.CharField(blank=True, max_length=50, verbose_name='存档-过程附件类型'),
        ),
        migrations.AddField(
            model_name='costprojectunified',
            name='archive_service_contract',
            field=models.FileField(blank=True, upload_to=eims_app.models.model_cost_unified.CostProjectUnified.archive_service_contract_upload_path, verbose_name='存档-服务合同'),
        ),
        migrations.AddField(
            model_name='costprojectunified',
            name='archive_service_contract_type',
            field=models.CharField(blank=True, max_length=50, verbose_name='存档-合同附件类型'),
        ),
        migrations.AddField(
            model_name='costprojectunified',
            name='archive_submission_material',
            field=models.FileField(blank=True, upload_to=eims_app.models.model_cost_unified.CostProjectUnified.archive_submission_material_upload_path, verbose_name='存档-送审资料'),
        ),
        migrations.AddField(
            model_name='costprojectunified',
            name='archive_submission_material_type',
            field=models.CharField(blank=True, max_length=50, verbose_name='存档-送审附件类型'),
        ),
    ]
