# Generated by Django 5.2 on 2026-03-25 16:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eims_app", "0020_contractapproval_initiation_time_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DynamicChoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("project.project_status", "项目状态"),
                            ("project.contract_category", "合同类别"),
                            ("projectdetail.project_status", "项目状态（详情）"),
                            ("projectdetail.contract_category", "合同类别（详情）"),
                            ("projectdetail.contract_status", "合同状态"),
                            ("projectdetail.settlement_status", "结算情况"),
                            ("projectdetail.construction_permit_status", "报建情况"),
                            ("projectdetail.entry_notice", "进场通知"),
                            ("projectdynamic.project_status", "项目动态状态"),
                            ("userprofile.gender", "性别"),
                            ("personnel.gender", "人员性别"),
                            ("employeecertificate.certificate_type", "证书类型"),
                            ("employeeallocation.allocation_status", "分配状态"),
                            ("contractapproval.status", "审批状态"),
                            ("contractapproval.approval_flow_type", "审批流程类型"),
                            ("contractapproval.approval_result", "审批结果"),
                            ("approvalattachment.file_type", "附件类型"),
                            ("approvalrecord.action", "审批操作"),
                            ("departmentmanager.role", "部门角色"),
                            ("approvalflowconfig.flow_type", "流程类型"),
                            ("workflowrole.name", "工作流角色"),
                            ("approvalflow.status", "工作流状态"),
                            ("flowaction.action", "工作流操作"),
                            ("userprofile.report_period", "填报周期"),
                            ("monthlyreport.status", "填报状态"),
                        ],
                        help_text="选择该选项所属的业务类别",
                        max_length=100,
                        verbose_name="选项类别",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="英文代码，如：not_started",
                        max_length=50,
                        verbose_name="选项代码",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="中文名称，如：未开工",
                        max_length=100,
                        verbose_name="选项名称",
                    ),
                ),
                (
                    "order",
                    models.IntegerField(
                        default=0, help_text="数字越小越靠前", verbose_name="排序"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="禁用后的选项将不在下拉列表中显示",
                        verbose_name="是否启用",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
            ],
            options={
                "verbose_name": "动态选项",
                "verbose_name_plural": "动态选项管理",
                "ordering": ["category", "order", "code"],
                "unique_together": {("category", "code")},
            },
        ),
    ]
