# Generated by Django 4.2.7 on 2026-04-19 22:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eims_app', '0020_costprojectunified_archive_audit_report_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostConsultingReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_type', models.CharField(choices=[('new_project', '新项目待分配'), ('task_assigned', '任务已分配'), ('compilation_start', '开始编制'), ('review_start', '开始审核'), ('archive_submit', '归档申请提交'), ('archive_approve', '归档审批待处理'), ('archive_receive', '档案待接收'), ('other', '其他')], default='other', max_length=30, verbose_name='提醒类型')),
                ('title', models.CharField(max_length=200, verbose_name='提醒标题')),
                ('content', models.TextField(verbose_name='提醒内容')),
                ('link_url', models.URLField(blank=True, help_text='点击提醒后跳转的页面地址', verbose_name='跳转链接')),
                ('status', models.CharField(choices=[('unread', '未读'), ('read', '已读')], db_index=True, default='unread', max_length=10, verbose_name='阅读状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='阅读时间')),
                ('project', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cost_reminders', to='eims_app.costprojectunified', verbose_name='关联项目')),
                ('receiver', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='received_cost_reminders', to=settings.AUTH_USER_MODEL, verbose_name='接收人')),
                ('sender', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_cost_reminders', to=settings.AUTH_USER_MODEL, verbose_name='发送人')),
                ('tenant', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='eims_app.tenant', verbose_name='所属公司')),
            ],
            options={
                'verbose_name': '造价咨询提醒',
                'verbose_name_plural': '造价咨询提醒管理',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['receiver', 'status'], name='eims_app_co_receive_ef3752_idx'), models.Index(fields=['tenant', 'status'], name='eims_app_co_tenant__d5531f_idx')],
            },
        ),
    ]
