# Generated by Django 4.2.7 on 2026-04-20 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eims_app', '0021_costconsultingreminder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costprojectunified',
            name='archive_status',
            field=models.CharField(choices=[('not_archived', '未归档'), ('archiving', '归档中'), ('pending_receive', '待接收'), ('rejected', '退回'), ('archived', '已归档')], default='not_archived', max_length=20, verbose_name='存档-归档状态'),
        ),
    ]
