# Generated by Django 5.2 on 2026-03-27 23:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eims_app", "0022_projectdetail_update_field_labels"),
    ]

    operations = [
        migrations.DeleteModel(
            name="InfoCollect",
        ),
        migrations.RemoveField(
            model_name="inspection",
            name="project",
        ),
        migrations.AlterModelOptions(
            name="outputpayment",
            options={
                "ordering": ["-month", "-create_time"],
                "verbose_name": "产值回款",
                "verbose_name_plural": "产值回款",
            },
        ),
        migrations.AlterUniqueTogether(
            name="outputpayment",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="personnel",
            name="project2",
            field=models.ForeignKey(
                blank=True,
                help_text="选择第二个项目（可选）",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="personnel_project2",
                to="eims_app.projectdetail",
                verbose_name="项目 2",
            ),
        ),
        migrations.AddField(
            model_name="personnel",
            name="project3",
            field=models.ForeignKey(
                blank=True,
                help_text="选择第三个项目（可选）",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="personnel_project3",
                to="eims_app.projectdetail",
                verbose_name="项目 3",
            ),
        ),
        migrations.AddField(
            model_name="personnel",
            name="project4",
            field=models.ForeignKey(
                blank=True,
                help_text="选择第四个项目（可选）",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="personnel_project4",
                to="eims_app.projectdetail",
                verbose_name="项目 4",
            ),
        ),
        migrations.AddField(
            model_name="personnel",
            name="project5",
            field=models.ForeignKey(
                blank=True,
                help_text="选择第五个项目（可选）",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="personnel_project5",
                to="eims_app.projectdetail",
                verbose_name="项目 5",
            ),
        ),
        migrations.AddField(
            model_name="personnel",
            name="project_code2",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                max_length=50,
                verbose_name="项目 2 编号",
            ),
        ),
        migrations.AddField(
            model_name="personnel",
            name="project_code3",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                max_length=50,
                verbose_name="项目 3 编号",
            ),
        ),
        migrations.AddField(
            model_name="personnel",
            name="project_code4",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                max_length=50,
                verbose_name="项目 4 编号",
            ),
        ),
        migrations.AddField(
            model_name="personnel",
            name="project_code5",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                max_length=50,
                verbose_name="项目 5 编号",
            ),
        ),
        migrations.AlterField(
            model_name="outputpayment",
            name="actual_payment",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=15,
                verbose_name="本月实际回款 (元)",
            ),
        ),
        migrations.AlterField(
            model_name="outputpayment",
            name="contract_receivable",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=15,
                verbose_name="合同应收款 (元)",
            ),
        ),
        migrations.AlterField(
            model_name="outputpayment",
            name="contract_total",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=15, verbose_name="合同总额 (元)"
            ),
        ),
        migrations.AlterField(
            model_name="outputpayment",
            name="cumulative_output",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="累计产值 (万元)",
            ),
        ),
        migrations.AlterField(
            model_name="outputpayment",
            name="cumulative_received",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=15,
                verbose_name="累计已收款 (元)",
            ),
        ),
        migrations.AlterField(
            model_name="outputpayment",
            name="month",
            field=models.CharField(max_length=7, verbose_name="月份"),
        ),
        migrations.AlterField(
            model_name="outputpayment",
            name="monthly_output",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="当月产值 (万元)",
            ),
        ),
        migrations.AlterField(
            model_name="outputpayment",
            name="near_term_receivable",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=15,
                verbose_name="近期待收款 (元)",
            ),
        ),
        migrations.AlterField(
            model_name="outputpayment",
            name="next_month_plan",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=15,
                verbose_name="下月计划收款 (元)",
            ),
        ),
        migrations.AlterField(
            model_name="outputpayment",
            name="next_month_request",
            field=models.TextField(blank=True, default="", verbose_name="下个月请款"),
        ),
        migrations.AlterField(
            model_name="outputpayment",
            name="operator",
            field=models.CharField(
                blank=True, default="", max_length=50, verbose_name="操作人"
            ),
        ),
        migrations.AlterField(
            model_name="outputpayment",
            name="output_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="当月产值 (万元)",
            ),
        ),
        migrations.AlterField(
            model_name="outputpayment",
            name="payment_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=15,
                verbose_name="本月实际回款 (元)",
            ),
        ),
        migrations.AlterField(
            model_name="outputpayment",
            name="payment_date",
            field=models.DateField(blank=True, null=True, verbose_name="回款日期"),
        ),
        migrations.AlterField(
            model_name="outputpayment",
            name="payment_method",
            field=models.CharField(
                blank=True, default="", max_length=50, verbose_name="回款方式"
            ),
        ),
        migrations.AlterField(
            model_name="outputpayment",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="output_payments",
                to="eims_app.projectdetail",
                verbose_name="项目",
            ),
        ),
        migrations.AlterField(
            model_name="outputpayment",
            name="project_code",
            field=models.CharField(
                db_index=True, max_length=50, verbose_name="项目编号"
            ),
        ),
        migrations.AlterField(
            model_name="personnel",
            name="department",
            field=models.CharField(
                db_index=True,
                default="",
                help_text="请输入所属部门",
                max_length=100,
                verbose_name="部门",
            ),
        ),
        migrations.AddIndex(
            model_name="outputpayment",
            index=models.Index(
                fields=["project_code", "month"], name="eims_app_ou_project_54df90_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="outputpayment",
            index=models.Index(
                fields=["project", "month"], name="eims_app_ou_project_997523_idx"
            ),
        ),
        migrations.DeleteModel(
            name="Inspection",
        ),
        migrations.RemoveField(
            model_name="outputpayment",
            name="is_deleted",
        ),
    ]
