# Generated by Django 4.2.7 on 2026-04-20 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eims_app', '0022_alter_costprojectunified_archive_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='costconsultingreminder',
            name='ignored_session',
            field=models.CharField(blank=True, help_text='本次登录期间忽略的提醒会话ID', max_length=100, verbose_name='忽略会话ID'),
        ),
        migrations.AddField(
            model_name='costconsultingreminder',
            name='snooze_until',
            field=models.DateTimeField(blank=True, help_text='延迟到该时间再次提醒', null=True, verbose_name='延迟提醒时间'),
        ),
        migrations.AlterField(
            model_name='costconsultingreminder',
            name='status',
            field=models.CharField(choices=[('unread', '未读'), ('read', '已读'), ('ignored', '已忽略')], db_index=True, default='unread', max_length=10, verbose_name='阅读状态'),
        ),
    ]
