# Generated by Django 4.2.7 on 2026-04-20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eims_app', '0023_costconsultingreminder_ignored_session_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='employee_code',
            new_name='personnel_code',
        ),
    ]
