# Generated by Django 5.2 on 2026-03-28 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eims_app", "0023_delete_infocollect_remove_inspection_project_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="email",
            field=models.EmailField(
                blank=True,
                help_text="填写电子邮箱",
                max_length=254,
                null=True,
                verbose_name="邮箱",
            ),
        ),
    ]
