# Generated by Django 5.2 on 2026-03-29 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eims_app", "0024_employee_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="personnelallocation",
            name="to_project",
            field=models.ForeignKey(
                blank=True,
                help_text="选择分配到的项目",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="to_projects",
                to="eims_app.projectdetail",
                verbose_name="分配项目",
            ),
        ),
        migrations.AlterField(
            model_name="personnelallocation",
            name="to_project_code",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="分配项目编号"
            ),
        ),
    ]
