# Generated by Django 4.2.7 on 2026-04-22 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eims_app', '0024_rename_employee_code_to_personnel_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='personnel_code',
            field=models.CharField(help_text='请输入唯一的人员编号', max_length=50, unique=True, verbose_name='人员编号'),
        ),
    ]
