# Generated by Django 5.2 on 2026-03-29 16:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eims_app", "0025_alter_personnelallocation_to_project_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SMSVerificationRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="是否删除"),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "phone",
                    models.CharField(
                        db_index=True, max_length=20, verbose_name="手机号码"
                    ),
                ),
                (
                    "verification_type",
                    models.CharField(
                        choices=[
                            ("login", "登录验证"),
                            ("reset_password", "重置密码"),
                            ("change_phone", "修改手机号"),
                            ("register", "注册验证"),
                        ],
                        max_length=20,
                        verbose_name="验证类型",
                    ),
                ),
                (
                    "verification_code",
                    models.CharField(max_length=10, verbose_name="验证码"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("success", "成功"),
                            ("failed", "失败"),
                            ("expired", "过期"),
                        ],
                        default="success",
                        max_length=20,
                        verbose_name="验证状态",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP 地址"
                    ),
                ),
                (
                    "user_agent",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="User-Agent"
                    ),
                ),
                ("expire_time", models.DateTimeField(verbose_name="过期时间")),
                (
                    "verified_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="验证时间"
                    ),
                ),
                ("remark", models.TextField(blank=True, verbose_name="备注")),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="关联用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "短信验证记录",
                "verbose_name_plural": "短信验证记录管理",
                "ordering": ("-create_time",),
            },
        ),
    ]
