# Generated by Django 5.2 on 2026-03-30 13:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("eims_app", "0027_notice_keywords_upload_person"),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='create_time',
            field=models.DateTimeField('创建时间', auto_now_add=True, default=django.utils.timezone.now, help_text='通知公告的创建时间（第一次发布时间）'),
            preserve_default=False,
        ),
    ]
