# Generated by Django 5.2 on 2026-03-30 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eims_app", "0028_add_create_time_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='publish_time',
            field=models.DateTimeField('发布时间', blank=True, null=True, help_text='系统自动设置，当状态从草稿改为已发布时'),
        ),
    ]
