# Generated by Django 5.2 on 2026-03-30 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eims_app", "0029_modify_publish_time_nullable"),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notice',
            name='publish_time',
        ),
    ]
