# Generated by Django 5.2 on 2026-03-30 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eims_app", "0030_remove_publish_time_field"),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notice',
            name='upload_person',
        ),
    ]
