# Generated by Django 5.2 on 2026-03-31 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eims_app", "0031_remove_upload_person_field"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="notice",
            options={
                "ordering": ["-create_time"],
                "verbose_name": "通知公告",
                "verbose_name_plural": "通知公告",
            },
        ),
        migrations.AddField(
            model_name="filemanage",
            name="file_format",
            field=models.CharField(
                blank=True,
                help_text="自动识别，只读",
                max_length=50,
                null=True,
                verbose_name="文件格式",
            ),
        ),
    ]
