# Generated by Django 5.2 on 2026-03-31 11:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eims_app", "0032_alter_notice_options_filemanage_file_format"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="departmentrole",
            name="supervisor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="supervised_employees",
                to=settings.AUTH_USER_MODEL,
                verbose_name="直属上级",
            ),
        ),
    ]
