# Generated by Django 4.2.7 on 2026-04-05 06:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eims_app', '0033_departmentrole_supervisor'),
    ]

    operations = [
        migrations.CreateModel(
            name='QRCodeLoginSession',
            fields=[
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='会话ID')),
                ('status', models.CharField(choices=[('pending', '等待扫码'), ('scanned', '已扫码'), ('confirmed', '已确认'), ('cancelled', '已取消'), ('expired', '已过期')], default='pending', max_length=20, verbose_name='状态')),
                ('scanned_at', models.DateTimeField(blank=True, null=True, verbose_name='扫码时间')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='确认时间')),
                ('expires_at', models.DateTimeField(verbose_name='过期时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('extra_data', models.JSONField(blank=True, default=dict, verbose_name='额外数据')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '二维码登录会话',
                'verbose_name_plural': '二维码登录会话',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['session_id', 'status'], name='eims_app_qr_session_b10af3_idx'), models.Index(fields=['expires_at'], name='eims_app_qr_expires_b2afeb_idx')],
            },
        ),
    ]
