# Generated by Django 4.2.7 on 2026-04-05 07:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eims_app', '0034_qrcodeloginsession'),
    ]

    operations = [
        migrations.CreateModel(
            name='WechatUserBinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openid', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='微信OpenID')),
                ('unionid', models.CharField(blank=True, db_index=True, default='', max_length=100, verbose_name='微信UnionID')),
                ('nickname', models.CharField(blank=True, max_length=100, verbose_name='微信昵称')),
                ('headimgurl', models.URLField(blank=True, verbose_name='微信头像')),
                ('sex', models.SmallIntegerField(default=0, verbose_name='性别')),
                ('country', models.CharField(blank=True, max_length=50, verbose_name='国家')),
                ('province', models.CharField(blank=True, max_length=50, verbose_name='省份')),
                ('city', models.CharField(blank=True, max_length=50, verbose_name='城市')),
                ('is_bound', models.BooleanField(default=True, verbose_name='是否已绑定')),
                ('bind_time', models.DateTimeField(auto_now_add=True, verbose_name='绑定时间')),
                ('last_login_time', models.DateTimeField(blank=True, null=True, verbose_name='最后登录时间')),
                ('extra_data', models.JSONField(blank=True, default=dict, verbose_name='额外数据')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wechat_bindings', to=settings.AUTH_USER_MODEL, verbose_name='系统用户')),
            ],
            options={
                'verbose_name': '微信用户绑定',
                'verbose_name_plural': '微信用户绑定',
                'indexes': [models.Index(fields=['openid'], name='eims_app_we_openid_c1cf12_idx'), models.Index(fields=['unionid'], name='eims_app_we_unionid_a32803_idx'), models.Index(fields=['user', 'is_bound'], name='eims_app_we_user_id_62f30b_idx')],
            },
        ),
        migrations.CreateModel(
            name='WechatQRCodeSession',
            fields=[
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='会话ID')),
                ('state', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='State参数')),
                ('status', models.CharField(choices=[('pending', '等待扫码'), ('scanned', '已扫码'), ('authorized', '已授权'), ('bound', '已绑定'), ('cancelled', '已取消'), ('expired', '已过期')], default='pending', max_length=20, verbose_name='状态')),
                ('code', models.CharField(blank=True, max_length=200, verbose_name='授权码')),
                ('openid', models.CharField(blank=True, max_length=100, verbose_name='OpenID')),
                ('unionid', models.CharField(blank=True, max_length=100, verbose_name='UnionID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('expires_at', models.DateTimeField(verbose_name='过期时间')),
                ('scanned_at', models.DateTimeField(blank=True, null=True, verbose_name='扫码时间')),
                ('authorized_at', models.DateTimeField(blank=True, null=True, verbose_name='授权时间')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '微信扫码登录会话',
                'verbose_name_plural': '微信扫码登录会话',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['state'], name='eims_app_we_state_a9e8c9_idx'), models.Index(fields=['status', 'expires_at'], name='eims_app_we_status_bf6e99_idx')],
            },
        ),
    ]
