# Generated by Django 4.2.7 on 2026-04-05 14:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eims_app', '0035_wechatuserbinding_wechatqrcodesession'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractapprovalrecord',
            name='next_approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_approval_records', to=settings.AUTH_USER_MODEL, verbose_name='下一步审批人'),
        ),
    ]
