# Generated by Django 4.2.7 on 2026-04-07 14:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eims_app', '0036_contractapprovalrecord_next_approver'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchiveApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='审批标题')),
                ('project_name', models.CharField(max_length=200, verbose_name='项目名称')),
                ('project_code', models.CharField(blank=True, max_length=50, verbose_name='项目编号')),
                ('initiation_time', models.DateTimeField(blank=True, help_text='审批流程的初始提交时间', null=True, verbose_name='发起时间')),
                ('archive_date', models.DateField(blank=True, null=True, verbose_name='归档日期')),
                ('archive_location', models.CharField(blank=True, help_text='如：档案室A-03柜', max_length=200, verbose_name='归档位置')),
                ('archive_period', models.CharField(choices=[('permanent', '永久'), ('long_term', '长期（30年）'), ('short_term', '短期（10年）')], default='long_term', max_length=50, verbose_name='归档期限')),
                ('total_files', models.IntegerField(default=0, verbose_name='文件总数')),
                ('total_pages', models.IntegerField(default=0, verbose_name='总页数')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('pending', '待审核'), ('reviewing', '审核中'), ('approved', '已通过'), ('rejected', '已退回'), ('cancelled', '已撤销')], default='draft', max_length=20, verbose_name='审批状态')),
                ('approval_flow_type', models.CharField(choices=[('user_selected', '由我选择审批人'), ('system_assigned', '由系统自动指派')], default='system_assigned', max_length=20, verbose_name='审批流程类型')),
                ('approval_level', models.IntegerField(default=1, help_text='1=部门级，2=上级', verbose_name='当前审批级别')),
                ('max_approval_level', models.IntegerField(default=2, help_text='默认 2 级审批', verbose_name='最大审批级别')),
                ('approval_result', models.CharField(blank=True, choices=[('archived', '已归档'), ('rejected', '审批未通过')], max_length=20, null=True, verbose_name='审批结果')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='提交时间')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='审批通过时间')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('applicant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archive_approvals', to=settings.AUTH_USER_MODEL, verbose_name='申请人')),
                ('auto_assigned_approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auto_assigned_archive_approvals', to=settings.AUTH_USER_MODEL, verbose_name='系统指派的审批人')),
                ('current_approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archive_approvals_to_handle', to=settings.AUTH_USER_MODEL, verbose_name='当前审批人')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archive_approvals', to='eims_app.department', verbose_name='申请部门')),
                ('initiator', models.ForeignKey(blank=True, help_text='审批流程的发起人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_archive_approvals', to=settings.AUTH_USER_MODEL, verbose_name='发起人')),
                ('selected_approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selected_archive_approvals', to=settings.AUTH_USER_MODEL, verbose_name='选择的审批人')),
                ('selected_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selected_archive_approvals', to='eims_app.department', verbose_name='选择的审批部门')),
            ],
            options={
                'verbose_name': '归档审批',
                'verbose_name_plural': '归档审批',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='contract',
            name='contract_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='合同金额 (元)'),
        ),
        migrations.CreateModel(
            name='ArchiveAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='archive_approvals/%Y/%m/', verbose_name='上传文件')),
                ('file_type', models.CharField(choices=[('contract', '合同协议'), ('supplement', '补充协议'), ('letter', '联系函'), ('report', '报告'), ('drawing', '图纸'), ('photo', '照片'), ('video', '视频'), ('other', '其他文件')], default='contract', max_length=20, verbose_name='文件类型')),
                ('file_name', models.CharField(max_length=255, verbose_name='文件名')),
                ('file_size', models.IntegerField(default=0, verbose_name='文件大小 (字节)')),
                ('pages', models.IntegerField(default=0, help_text='文档页数', verbose_name='页数')),
                ('document_date', models.DateField(blank=True, null=True, verbose_name='成文日期')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('is_deleted', models.BooleanField(default=False)),
                ('approval', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='eims_app.archiveapproval', verbose_name='所属审批')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='上传人')),
            ],
            options={
                'verbose_name': '归档附件',
                'verbose_name_plural': '归档附件',
                'ordering': ['document_date', 'file_type'],
            },
        ),
        migrations.CreateModel(
            name='ArchiveApprovalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('submit', '提交'), ('approve', '同意'), ('reject', '退回'), ('cancel', '撤销'), ('comment', '评论')], max_length=20, verbose_name='操作类型')),
                ('comment', models.TextField(blank=True, verbose_name='审批意见')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('approval', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_records', to='eims_app.archiveapproval', verbose_name='所属审批')),
                ('next_approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_archive_approval_records', to=settings.AUTH_USER_MODEL, verbose_name='下一步审批人')),
                ('operator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
            ],
            options={
                'verbose_name': '归档审批记录',
                'verbose_name_plural': '归档审批记录',
                'ordering': ['created_at'],
            },
        ),
    ]
