# Generated by Django 4.2.7 on 2026-04-07 15:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eims_app', '0037_archiveapproval_alter_contract_contract_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SealApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='审批标题')),
                ('initiation_time', models.DateTimeField(blank=True, help_text='审批流程的初始提交时间', null=True, verbose_name='发起时间')),
                ('seal_type', models.CharField(choices=[('official_seal', '公章'), ('legal_representative_seal', '法人章'), ('legal_representative_signature', '法人签字章'), ('professional_seal', '执业印章'), ('contract_seal', '合同专用章'), ('finance_seal', '财务专用章'), ('invoice_seal', '发票专用章'), ('other', '其他印章')], max_length=50, verbose_name='印章名称')),
                ('seal_count', models.IntegerField(default=1, help_text='需要盖章的份数', verbose_name='盖章数量')),
                ('document_name', models.CharField(max_length=200, verbose_name='文件名称')),
                ('document_type', models.CharField(blank=True, help_text='如：合同、报告、证明等', max_length=50, verbose_name='文件类型')),
                ('project_name', models.CharField(blank=True, max_length=200, verbose_name='关联项目')),
                ('project_code', models.CharField(blank=True, max_length=50, verbose_name='项目编号')),
                ('usage_purpose', models.TextField(help_text='说明用印的具体用途', verbose_name='用印用途')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('pending', '待审核'), ('reviewing', '审核中'), ('approved', '已通过'), ('rejected', '已退回'), ('cancelled', '已撤销')], default='draft', max_length=20, verbose_name='审批状态')),
                ('approval_flow_type', models.CharField(choices=[('user_selected', '由我选择审批人'), ('system_assigned', '由系统自动指派')], default='system_assigned', max_length=20, verbose_name='审批流程类型')),
                ('approval_level', models.IntegerField(default=1, help_text='1=部门级，2=上级', verbose_name='当前审批级别')),
                ('max_approval_level', models.IntegerField(default=2, help_text='默认 2 级审批', verbose_name='最大审批级别')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='提交时间')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='审批通过时间')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('applicant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seal_approvals', to=settings.AUTH_USER_MODEL, verbose_name='申请人')),
                ('auto_assigned_approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auto_assigned_seal_approvals', to=settings.AUTH_USER_MODEL, verbose_name='系统指派的审批人')),
                ('current_approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seal_approvals_to_handle', to=settings.AUTH_USER_MODEL, verbose_name='当前审批人')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seal_approvals', to='eims_app.department', verbose_name='申请部门')),
                ('initiator', models.ForeignKey(blank=True, help_text='审批流程的发起人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_seal_approvals', to=settings.AUTH_USER_MODEL, verbose_name='发起人')),
                ('selected_approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selected_seal_approvals', to=settings.AUTH_USER_MODEL, verbose_name='选择的审批人')),
                ('selected_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selected_seal_approvals', to='eims_app.department', verbose_name='选择的审批部门')),
            ],
            options={
                'verbose_name': '用印审批',
                'verbose_name_plural': '用印审批',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SealAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='seal_approvals/%Y/%m/', verbose_name='上传文件')),
                ('file_type', models.CharField(choices=[('document', '文件原件'), ('attachment', '附件材料'), ('other', '其他资料')], default='document', max_length=20, verbose_name='文件类型')),
                ('file_name', models.CharField(max_length=255, verbose_name='文件名')),
                ('file_size', models.IntegerField(default=0, verbose_name='文件大小 (字节)')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('is_deleted', models.BooleanField(default=False)),
                ('approval', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='eims_app.sealapproval', verbose_name='所属审批')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='上传人')),
            ],
            options={
                'verbose_name': '用印附件',
                'verbose_name_plural': '用印附件',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='SealApprovalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('submit', '提交'), ('approve', '同意'), ('reject', '退回'), ('cancel', '撤销'), ('comment', '评论')], max_length=20, verbose_name='操作类型')),
                ('comment', models.TextField(blank=True, verbose_name='审批意见')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('approval', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_records', to='eims_app.sealapproval', verbose_name='所属审批')),
                ('next_approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_seal_approval_records', to=settings.AUTH_USER_MODEL, verbose_name='下一步审批人')),
                ('operator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
            ],
            options={
                'verbose_name': '用印审批记录',
                'verbose_name_plural': '用印审批记录',
                'ordering': ['created_at'],
            },
        ),
    ]
