# Generated by Django 4.2.7 on 2026-04-09 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eims_app', '0038_sealapproval_sealattachment_sealapprovalrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectdetail',
            name='construction_permit_status',
            field=models.CharField(blank=True, choices=[('not_started', '未办理'), ('in_progress', '办理中'), ('completed', '已办理')], default='', max_length=20, verbose_name='报建情况'),
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='公司的唯一标识代码，如：COMPANY_A', max_length=50, unique=True, verbose_name='公司代码')),
                ('name', models.CharField(max_length=200, verbose_name='公司名称')),
                ('short_name', models.CharField(max_length=50, verbose_name='简称')),
                ('logo', models.ImageField(blank=True, help_text='公司Logo图片', null=True, upload_to='tenants/logos/', verbose_name='Logo')),
                ('contact_person', models.CharField(blank=True, max_length=100, verbose_name='联系人')),
                ('contact_phone', models.CharField(blank=True, max_length=20, verbose_name='联系电话')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='联系邮箱')),
                ('address', models.TextField(blank=True, verbose_name='公司地址')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '租户公司',
                'verbose_name_plural': '租户公司管理',
                'ordering': ['code'],
                'indexes': [models.Index(fields=['code'], name='eims_app_te_code_057cf1_idx'), models.Index(fields=['is_active'], name='eims_app_te_is_acti_57eb38_idx')],
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='用户所属的公司，数据隔离依据', null=True, on_delete=django.db.models.deletion.PROTECT, to='eims_app.tenant', verbose_name='所属公司'),
        ),
    ]
