# Generated by Django 4.2.7 on 2026-04-09 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eims_app', '0039_alter_projectdetail_construction_permit_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='archiveapproval',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='数据隔离依据', null=True, on_delete=django.db.models.deletion.PROTECT, to='eims_app.tenant', verbose_name='所属公司'),
        ),
        migrations.AddField(
            model_name='contract',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='数据隔离依据', null=True, on_delete=django.db.models.deletion.PROTECT, to='eims_app.tenant', verbose_name='所属公司'),
        ),
        migrations.AddField(
            model_name='contractapproval',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='数据隔离依据', null=True, on_delete=django.db.models.deletion.PROTECT, to='eims_app.tenant', verbose_name='所属公司'),
        ),
        migrations.AddField(
            model_name='department',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='数据隔离依据', null=True, on_delete=django.db.models.deletion.PROTECT, to='eims_app.tenant', verbose_name='所属公司'),
        ),
        migrations.AddField(
            model_name='employee',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='数据隔离依据', null=True, on_delete=django.db.models.deletion.PROTECT, to='eims_app.tenant', verbose_name='所属公司'),
        ),
        migrations.AddField(
            model_name='filemanage',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='数据隔离依据', null=True, on_delete=django.db.models.deletion.PROTECT, to='eims_app.tenant', verbose_name='所属公司'),
        ),
        migrations.AddField(
            model_name='notice',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='数据隔离依据', null=True, on_delete=django.db.models.deletion.PROTECT, to='eims_app.tenant', verbose_name='所属公司'),
        ),
        migrations.AddField(
            model_name='outputpayment',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='数据隔离依据', null=True, on_delete=django.db.models.deletion.PROTECT, to='eims_app.tenant', verbose_name='所属公司'),
        ),
        migrations.AddField(
            model_name='personnel',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='数据隔离依据', null=True, on_delete=django.db.models.deletion.PROTECT, to='eims_app.tenant', verbose_name='所属公司'),
        ),
        migrations.AddField(
            model_name='personnelallocation',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='数据隔离依据', null=True, on_delete=django.db.models.deletion.PROTECT, to='eims_app.tenant', verbose_name='所属公司'),
        ),
        migrations.AddField(
            model_name='personnelcertificate',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='数据隔离依据', null=True, on_delete=django.db.models.deletion.PROTECT, to='eims_app.tenant', verbose_name='所属公司'),
        ),
        migrations.AddField(
            model_name='projectdetail',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='数据隔离依据', null=True, on_delete=django.db.models.deletion.PROTECT, to='eims_app.tenant', verbose_name='所属公司'),
        ),
        migrations.AddField(
            model_name='projectdynamic',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='数据隔离依据', null=True, on_delete=django.db.models.deletion.PROTECT, to='eims_app.tenant', verbose_name='所属公司'),
        ),
        migrations.AddField(
            model_name='sealapproval',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='数据隔离依据', null=True, on_delete=django.db.models.deletion.PROTECT, to='eims_app.tenant', verbose_name='所属公司'),
        ),
    ]
