# Generated by Django 4.2.7 on 2026-04-09 09:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eims_app', '0040_archiveapproval_tenant_contract_tenant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='用户默认所属公司，用于数据隔离和登录默认选择', null=True, on_delete=django.db.models.deletion.PROTECT, to='eims_app.tenant', verbose_name='默认公司'),
        ),
        migrations.CreateModel(
            name='UserTenantRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=False, help_text='每个用户只能有一个主公司', verbose_name='是否主公司')),
                ('remark', models.CharField(blank=True, help_text='如：全职/兼职/顾问等', max_length=200, verbose_name='备注')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eims_app.tenant', verbose_name='公司')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户公司关联',
                'verbose_name_plural': '用户公司关联管理',
                'indexes': [models.Index(fields=['user', 'is_primary'], name='eims_app_us_user_id_cc837d_idx'), models.Index(fields=['tenant'], name='eims_app_us_tenant__5aeb80_idx')],
                'unique_together': {('user', 'tenant')},
            },
        ),
    ]
