# Generated by Django 4.2.7 on 2026-04-10 00:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eims_app', '0041_add_user_tenant_relation'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='模块的唯一标识代码', max_length=50, unique=True, verbose_name='模块代码')),
                ('name', models.CharField(max_length=100, verbose_name='模块名称')),
                ('icon', models.CharField(default='bi-folder', help_text='Bootstrap Icons 类名，如：bi-clipboard-data', max_length=50, verbose_name='图标')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('sort_order', models.IntegerField(default=0, help_text='数字越小越靠前', verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '业务模块',
                'verbose_name_plural': '业务模块管理',
                'ordering': ['sort_order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='TenantModulePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True, help_text='勾选表示该公司可以使用此模块', verbose_name='是否启用')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_permissions', to='eims_app.tenantmodule', verbose_name='业务模块')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_permissions', to='eims_app.tenant', verbose_name='租户公司')),
            ],
            options={
                'verbose_name': '租户模块权限',
                'verbose_name_plural': '租户模块权限管理',
                'ordering': ['tenant', 'module__sort_order'],
                'indexes': [models.Index(fields=['tenant', 'is_enabled'], name='eims_app_te_tenant__c78da5_idx'), models.Index(fields=['module', 'is_enabled'], name='eims_app_te_module__8bd613_idx')],
                'unique_together': {('tenant', 'module')},
            },
        ),
    ]
